// Mais listas de 10 itens. Mesmo formato de data.js.
// Listas de opinião ou de popularidade não têm dado oficial: a fonte diz "Curadoria Tten".

const CUR = "Curadoria Tten (ranking de opinião)";
const POP = "Curadoria Tten: do mais lembrado ao menos óbvio";

CATEGORIES.push(
  { id: "personagens", label: "Personagens" },
  { id: "comida", label: "Comida e bebida" },
  { id: "diaadia", label: "Dia a dia" },
);

LISTS.push(
  // ───────────── Heróis ─────────────
  { id: "mcu-fortes", cat: "herois", title: "Os 10 Vingadores mais fortes do cinema", source: CUR,
    items: ["Capitã Marvel", "Feiticeira Escarlate|Wanda", "Thor", "Hulk", "Doutor Estranho", "Visão", "Homem de Ferro|Tony Stark", "Homem-Aranha", "Pantera Negra", "Capitão América"] },
  { id: "dc-fortes", cat: "herois", title: "Os 10 heróis mais fortes da DC", source: CUR,
    items: ["Superman", "Mulher-Maravilha", "Shazam", "Lanterna Verde", "Flash", "Caçador de Marte", "Supergirl", "Aquaman", "Ciborgue", "Batman"] },
  { id: "viloes-marvel", cat: "herois", title: "Os 10 vilões mais poderosos da Marvel", source: CUR,
    items: ["Thanos", "Galactus", "Dormammu", "Apocalipse", "Magneto", "Kang", "Ultron", "Doutor Destino", "Loki", "Caveira Vermelha"] },
  { id: "viloes-dc", cat: "herois", title: "Os 10 vilões mais poderosos da DC", source: CUR,
    items: ["Darkseid", "Apocalypse|Apocalipse", "General Zod|Zod", "Brainiac", "Sinestro", "Lex Luthor", "Bane", "Coringa", "Arlequina", "Pinguim"] },
  { id: "xmen-fortes", cat: "herois", title: "Os 10 X-Men mais fortes", source: CUR,
    items: ["Jean Grey|Fênix", "Professor X|Xavier|Charles Xavier", "Tempestade", "Vampira", "Wolverine", "Ciclope", "Colossus", "Noturno", "Fera", "Gambit"] },
  { id: "herois-inteligentes", cat: "herois", title: "Os 10 heróis mais inteligentes", source: CUR,
    items: ["Senhor Fantástico|Reed Richards", "Homem de Ferro|Tony Stark", "Bruce Banner|Hulk", "Shuri", "Batman", "Homem-Formiga|Hank Pym", "Doutor Estranho", "Homem-Aranha|Peter Parker", "Professor X|Xavier", "Ciborgue"] },
  { id: "herois-populares", cat: "herois", title: "Os 10 super-heróis mais populares", source: POP,
    items: ["Homem-Aranha", "Batman", "Superman", "Homem de Ferro", "Mulher-Maravilha", "Capitão América", "Hulk", "Thor", "Flash", "Pantera Negra"] },
  { id: "liga-justica", cat: "herois", title: "Os 10 membros mais famosos da Liga da Justiça", source: POP,
    items: ["Superman", "Batman", "Mulher-Maravilha", "Flash", "Aquaman", "Lanterna Verde", "Ciborgue", "Caçador de Marte", "Shazam", "Arqueiro Verde"] },
  { id: "viloes-aranha", cat: "herois", title: "Os 10 vilões mais famosos do Homem-Aranha", source: POP,
    items: ["Duende Verde", "Venom", "Doutor Octopus|Doc Ock", "Electro", "Lagarto", "Homem-Areia", "Abutre", "Mysterio", "Rino", "Kraven"] },

  // ───────────── Animes ─────────────
  { id: "dbs-fortes", cat: "animes", title: "Os 10 personagens mais fortes de Dragon Ball Super", source: CUR,
    items: ["Goku", "Bills|Beerus", "Whis", "Vegeta", "Jiren", "Broly", "Gohan", "Freeza", "Hit", "Piccolo"] },
  { id: "naruto-fortes", cat: "animes", title: "Os 10 personagens mais fortes de Naruto", source: CUR,
    items: ["Naruto", "Sasuke", "Kaguya", "Madara", "Hashirama", "Obito", "Itachi", "Minato", "Pain|Nagato", "Kakashi"] },
  { id: "goku-transformacoes", cat: "animes", title: "As transformações do Goku em ordem de aparição", source: "Dragon Ball (Akira Toriyama)",
    items: ["Oozaru|Macaco gigante", "Kaioken", "Super Saiyajin|SSJ", "Super Saiyajin 2|SSJ2", "Super Saiyajin 3|SSJ3", "Super Saiyajin 4|SSJ4", "Super Saiyajin Deus|SSJ Deus", "Super Saiyajin Blue|SSJ Blue", "Instinto Superior Incompleto", "Instinto Superior Completo|Instinto Superior"] },
  { id: "miyazaki", cat: "animes", title: "Os filmes de Hayao Miyazaki a partir de Nausicaä", source: "Studio Ghibli",
    items: ["Nausicaä do Vale do Vento|Nausicaa", "O Castelo no Céu|Laputa", "Meu Amigo Totoro|Totoro", "O Serviço de Entregas da Kiki|Kiki", "Porco Rosso", "Princesa Mononoke|Mononoke", "A Viagem de Chihiro|Chihiro", "O Castelo Animado", "Ponyo", "Vidas ao Vento"] },
  { id: "animes-famosos", cat: "animes", title: "Os 10 animes mais famosos no Brasil", source: POP,
    items: ["Naruto", "Dragon Ball", "One Piece", "Pokémon", "Cavaleiros do Zodíaco", "Attack on Titan|Shingeki no Kyojin", "Death Note", "Demon Slayer|Kimetsu no Yaiba", "Jujutsu Kaisen", "Fullmetal Alchemist"] },
  { id: "naruto-personagens", cat: "animes", title: "Os 10 personagens mais lembrados de Naruto", source: POP,
    items: ["Naruto", "Sasuke", "Sakura", "Kakashi", "Itachi", "Hinata", "Gaara", "Jiraiya", "Rock Lee", "Shikamaru"] },

  // ───────────── Games ─────────────
  { id: "pokedex-4", cat: "games", title: "Os Pokémon de nº 31 a 40 da Pokédex", source: "Pokédex Nacional",
    items: ["Nidoqueen", "Nidoran♂|Nidoran|Nidoran macho", "Nidorino", "Nidoking", "Clefairy", "Clefable", "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff"] },
  { id: "pokedex-5", cat: "games", title: "Os Pokémon de nº 41 a 50 da Pokédex", source: "Pokédex Nacional",
    items: ["Zubat", "Golbat", "Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth", "Diglett"] },
  { id: "pokedex-6", cat: "games", title: "Os Pokémon de nº 51 a 60 da Pokédex", source: "Pokédex Nacional",
    items: ["Dugtrio", "Meowth", "Persian", "Psyduck", "Golduck", "Mankey", "Primeape", "Growlithe", "Arcanine", "Poliwag"] },
  { id: "pokedex-final", cat: "games", title: "Os últimos 10 Pokémon da 1ª geração (nº 142 a 151)", source: "Pokédex Nacional",
    items: ["Aerodactyl", "Snorlax", "Articuno", "Zapdos", "Moltres", "Dratini", "Dragonair", "Dragonite", "Mewtwo", "Mew"] },
  { id: "pokemon-lendarios", cat: "games", title: "Os 10 primeiros Pokémon lendários (pela Pokédex)", source: "Pokédex Nacional (sem os míticos)",
    items: ["Articuno", "Zapdos", "Moltres", "Mewtwo", "Raikou", "Entei", "Suicune", "Lugia", "Ho-Oh", "Regirock"] },
  { id: "consoles-nintendo", cat: "games", title: "Os consoles da Nintendo em ordem, a partir do NES", source: "Nintendo",
    items: ["NES|Nintendinho|Famicom", "Game Boy", "Super Nintendo|SNES", "Virtual Boy", "Nintendo 64|N64", "Game Boy Color", "Game Boy Advance|GBA", "GameCube", "Nintendo DS|DS", "Wii"] },
  { id: "mario-personagens", cat: "games", title: "Os 10 personagens mais famosos do universo Mario", source: POP,
    items: ["Mario", "Luigi", "Princesa Peach|Peach", "Bowser", "Yoshi", "Toad", "Donkey Kong", "Wario", "Daisy", "Waluigi"] },
  { id: "minecraft-mobs", cat: "games", title: "Os 10 mobs mais famosos do Minecraft", source: POP,
    items: ["Creeper", "Zumbi|Zombie", "Esqueleto|Skeleton", "Enderman", "Aranha|Spider", "Aldeão|Villager", "Porco|Pig", "Vaca|Cow", "Ender Dragon|Dragão do Fim", "Wither"] },
  { id: "jogos-famosos", cat: "games", title: "Os 10 videogames mais famosos de todos os tempos", source: POP,
    items: ["Minecraft", "GTA|GTA V|Grand Theft Auto", "Super Mario Bros.|Super Mario|Mario", "Tetris", "Fortnite", "Pokémon", "FIFA|EA FC", "Call of Duty", "The Sims", "Pac-Man"] },
  { id: "personagens-games", cat: "games", title: "Os 10 personagens de videogame mais famosos", source: POP,
    items: ["Mario", "Sonic", "Pikachu", "Pac-Man", "Link", "Lara Croft", "Kratos", "Master Chief", "Steve", "Donkey Kong"] },
  { id: "street-fighter", cat: "games", title: "Os 10 lutadores mais famosos de Street Fighter", source: POP,
    items: ["Ryu", "Ken", "Chun-Li", "Guile", "Blanka", "Zangief", "Dhalsim", "M. Bison|Bison", "E. Honda|Honda", "Sagat"] },
  { id: "jogos-celular", cat: "games", title: "Os 10 jogos de celular mais famosos", source: POP,
    items: ["Candy Crush", "Subway Surfers", "Free Fire", "Clash Royale", "Pokémon GO", "Angry Birds", "Clash of Clans", "Among Us", "Roblox", "Fruit Ninja"] },

  // ───────────── Futebol ─────────────
  { id: "artilheiros-selecao", cat: "futebol", title: "Os 10 maiores artilheiros da Seleção Brasileira", source: "CBF (jogos oficiais, até 2025)",
    items: ["Neymar", "Pelé", "Ronaldo|Ronaldo Fenômeno", "Romário", "Zico", "Bebeto", "Rivaldo", "Jairzinho", "Ronaldinho|Ronaldinho Gaúcho", "Ademir de Menezes|Ademir"] },
  { id: "melhores-fifa", cat: "futebol", title: "Os 10 primeiros vencedores diferentes do prêmio de Melhor do Mundo da FIFA (desde 1991)", source: "FIFA",
    items: ["Lothar Matthäus|Matthaus", "Marco van Basten|Van Basten", "Roberto Baggio|Baggio", "Romário", "George Weah|Weah", "Ronaldo|Ronaldo Fenômeno", "Zinédine Zidane|Zidane", "Rivaldo", "Luís Figo|Figo", "Ronaldinho|Ronaldinho Gaúcho"] },
  { id: "copa-do-brasil", cat: "futebol", title: "Os 10 primeiros campeões diferentes da Copa do Brasil", source: "CBF",
    items: ["Grêmio", "Flamengo", "Criciúma", "Internacional|Inter", "Cruzeiro", "Corinthians", "Palmeiras", "Juventude", "Santo André", "Paulista"] },
  { id: "brasileirao-71", cat: "futebol", title: "Os 10 primeiros campeões diferentes do Brasileirão (a partir de 1971)", source: "CBF",
    items: ["Atlético Mineiro|Atlético-MG|Galo", "Palmeiras", "Vasco|Vasco da Gama", "Internacional|Inter", "São Paulo", "Guarani", "Flamengo", "Grêmio", "Fluminense", "Coritiba"] },
  { id: "numeracao", cat: "futebol", title: "A numeração clássica das camisas do 1 ao 10", source: "Tradição do futebol brasileiro",
    items: ["Goleiro", "Lateral-direito|Lateral direito", "Zagueiro|Beque", "Quarto-zagueiro|Quarto zagueiro", "Volante", "Lateral-esquerdo|Lateral esquerdo", "Ponta-direita|Ponta direita", "Meia|Meio-campo|Meio campo", "Centroavante|Atacante", "Meia-armador|Armador|Camisa 10"] },
  { id: "times-europeus", cat: "futebol", title: "Os 10 clubes europeus mais famosos", source: POP,
    items: ["Real Madrid", "Barcelona|Barça", "Manchester United", "Bayern de Munique|Bayern", "Liverpool", "Juventus", "Milan|AC Milan", "Paris Saint-Germain|PSG", "Chelsea", "Manchester City"] },
  { id: "craques-brasil", cat: "futebol", title: "Os 10 maiores craques brasileiros da história", source: CUR,
    items: ["Pelé", "Ronaldo|Ronaldo Fenômeno", "Garrincha", "Zico", "Romário", "Ronaldinho|Ronaldinho Gaúcho", "Neymar", "Kaká", "Rivaldo", "Sócrates"] },
  { id: "estadios-brasil", cat: "futebol", title: "Os 10 estádios mais famosos do Brasil", source: POP,
    items: ["Maracanã", "Morumbi|MorumBIS", "Mineirão", "Neo Química Arena|Arena Corinthians|Itaquerão", "Allianz Parque", "Beira-Rio", "Arena do Grêmio", "Vila Belmiro", "São Januário", "Castelão"] },
  { id: "bordoes-narrador", cat: "futebol", title: "Bordões de narrador de futebol", source: POP,
    items: ["Gooool!|~gol|~goool|~gooool", "Haja coração!|~coracao", "Pode isso, Arnaldo?|~arnaldo", "É tetra!|~tetra", "Sai que é sua, Taffarel!|~taffarel", "Olha o que ele fez!|~olha o que ele fez", "Que golaço!|~golaco", "Acabou! É campeão!|~campeao|~acabou", "Ripa na chulipa e pimba na gorduchinha|~chulipa|~gorduchinha", "Bola pro mato que o jogo é de campeonato|~mato"] },
  { id: "camisas-10", cat: "futebol", title: "Os 10 camisas 10 mais famosos", source: POP,
    items: ["Pelé", "Maradona", "Messi", "Zico", "Ronaldinho|Ronaldinho Gaúcho", "Neymar", "Zidane", "Kaká", "Rivaldo", "Platini"] },

  // ───────────── Esporte ─────────────
  { id: "olimpiadas-2", cat: "esporte", title: "As cidades-sede das Olimpíadas de Verão de 1996 a 2032", source: "COI",
    items: ["Atlanta", "Sydney", "Atenas", "Pequim", "Londres", "Rio de Janeiro|Rio", "Tóquio", "Paris", "Los Angeles", "Brisbane"] },
  { id: "nba-campeoes", cat: "esporte", title: "Os 10 primeiros campeões diferentes da NBA a partir de 1991", source: "NBA",
    items: ["Chicago Bulls|Bulls", "Houston Rockets|Rockets", "San Antonio Spurs|Spurs", "Los Angeles Lakers|Lakers", "Detroit Pistons|Pistons", "Miami Heat|Heat", "Boston Celtics|Celtics", "Dallas Mavericks|Mavericks", "Golden State Warriors|Warriors", "Cleveland Cavaliers|Cavaliers"] },
  { id: "esportes-populares", cat: "esporte", title: "Os 10 esportes mais populares do mundo", source: POP,
    items: ["Futebol", "Basquete", "Críquete", "Tênis", "Vôlei|Voleibol", "Fórmula 1|F1|Automobilismo", "Beisebol", "Golfe", "Futebol americano", "Rúgbi"] },
  { id: "pilotos-brasileiros", cat: "esporte", title: "Os 10 pilotos brasileiros mais famosos da Fórmula 1", source: POP,
    items: ["Ayrton Senna|Senna", "Nelson Piquet|Piquet", "Emerson Fittipaldi|Fittipaldi", "Rubens Barrichello|Barrichello|Rubinho", "Felipe Massa|Massa", "Gabriel Bortoleto|Bortoleto", "Felipe Nasr|Nasr", "Bruno Senna", "Nelsinho Piquet", "Lucas di Grassi|Di Grassi"] },
  { id: "atletas-brasileiros", cat: "esporte", title: "Os 10 atletas brasileiros mais famosos (fora o futebol masculino)", source: POP,
    items: ["Ayrton Senna|Senna", "Rebeca Andrade", "Guga|Gustavo Kuerten", "Oscar Schmidt", "Marta", "Gabriel Medina|Medina", "Anderson Silva", "Rayssa Leal", "César Cielo|Cielo", "Hortência"] },

  // ───────────── Filmes ─────────────
  { id: "spielberg", cat: "filmes", title: "Os 10 primeiros filmes de Steven Spielberg a partir de Tubarão", source: "Filmografia oficial",
    items: ["Tubarão|Jaws", "Contatos Imediatos do Terceiro Grau|Contatos Imediatos", "1941", "Os Caçadores da Arca Perdida|Indiana Jones", "E.T.|ET|E.T. o Extraterrestre", "Indiana Jones e o Templo da Perdição|Templo da Perdição", "A Cor Púrpura", "Império do Sol", "Indiana Jones e a Última Cruzada|Última Cruzada", "Além da Eternidade"] },
  { id: "tim-burton", cat: "filmes", title: "Os 10 primeiros filmes de Tim Burton", source: "Filmografia oficial",
    items: ["As Grandes Aventuras de Pee-wee|Pee-wee", "Os Fantasmas se Divertem|Beetlejuice", "Batman", "Edward Mãos de Tesoura", "Batman: O Retorno|Batman O Retorno", "Ed Wood", "Marte Ataca!|Marte Ataca", "A Lenda do Cavaleiro sem Cabeça|Cavaleiro sem Cabeça", "Planeta dos Macacos", "Peixe Grande"] },
  { id: "jogos-mortais", cat: "filmes", title: "Os 10 filmes de Jogos Mortais em ordem", source: "Lionsgate",
    items: ["Jogos Mortais|Jogos Mortais 1|Saw", "Jogos Mortais 2", "Jogos Mortais 3", "Jogos Mortais 4", "Jogos Mortais 5", "Jogos Mortais 6", "Jogos Mortais: O Final|Jogos Mortais 7|O Final", "Jigsaw|Jogos Mortais: Jigsaw", "Espiral|Espiral: O Legado de Jogos Mortais", "Jogos Mortais X|Jogos Mortais 10"] },
  { id: "disney-2010", cat: "filmes", title: "Os filmes da Disney Animation de 2010 a 2021", source: "Walt Disney Animation Studios",
    items: ["Enrolados", "O Ursinho Pooh|Ursinho Pooh", "Detona Ralph", "Frozen|Frozen: Uma Aventura Congelante", "Operação Big Hero|Big Hero", "Zootopia", "Moana", "WiFi Ralph|Detona Ralph 2", "Frozen II|Frozen 2", "Raya e o Último Dragão|Raya"] },
  { id: "oscar-80", cat: "filmes", title: "Vencedores do Oscar de Melhor Filme (cerimônias de 1981 a 1990)", source: "Academia de Hollywood",
    items: ["Gente como a Gente", "Carruagens de Fogo", "Gandhi", "Laços de Ternura", "Amadeus", "Entre Dois Amores|Out of Africa", "Platoon", "O Último Imperador", "Rain Man", "Conduzindo Miss Daisy"] },
  { id: "oscar-recentes", cat: "filmes", title: "Vencedores do Oscar de Melhor Filme (cerimônias de 2016 a 2025)", source: "Academia de Hollywood",
    items: ["Spotlight: Segredos Revelados|Spotlight", "Moonlight: Sob a Luz do Luar|Moonlight", "A Forma da Água", "Green Book: O Guia|Green Book", "Parasita|Parasite", "Nomadland", "No Ritmo do Coração|CODA", "Tudo em Todo o Lugar ao Mesmo Tempo", "Oppenheimer", "Anora"] },
  { id: "filmes-natal", cat: "filmes", title: "Os 10 filmes de Natal mais clássicos", source: POP,
    items: ["Esqueceram de Mim", "O Grinch", "Duro de Matar", "Um Duende em Nova York|Elf", "O Estranho Mundo de Jack", "Simplesmente Amor", "A Felicidade Não se Compra", "Milagre na Rua 34", "O Expresso Polar", "Meu Papai é Noel"] },
  { id: "filmes-terror", cat: "filmes", title: "Os 10 filmes de terror mais clássicos", source: POP,
    items: ["O Exorcista", "It: A Coisa|It", "Invocação do Mal", "O Iluminado", "Pânico", "Sexta-Feira 13", "A Hora do Pesadelo", "Halloween", "O Chamado", "Atividade Paranormal"] },
  { id: "animacoes-amadas", cat: "filmes", title: "As 10 animações mais amadas", source: POP,
    items: ["O Rei Leão", "Toy Story", "Shrek", "Frozen", "Procurando Nemo", "Divertida Mente", "Up: Altas Aventuras|Up", "Moana", "Os Incríveis", "Carros"] },
  { id: "filmes-brasileiros", cat: "filmes", title: "Os 10 filmes brasileiros mais famosos", source: POP,
    items: ["Cidade de Deus", "Tropa de Elite", "O Auto da Compadecida", "Central do Brasil", "Ainda Estou Aqui", "Minha Mãe é uma Peça", "Bacurau", "Que Horas Ela Volta?|Que Horas Ela Volta", "Carandiru", "O Pagador de Promessas"] },

  // ───────────── Personagens ─────────────
  { id: "chaves", cat: "personagens", title: "Os 10 personagens mais lembrados de Chaves", source: POP,
    items: ["Chaves", "Seu Madruga", "Quico", "Chiquinha", "Dona Florinda", "Professor Girafales|Girafales", "Seu Barriga", "Dona Clotilde|Bruxa do 71", "Nhonho", "Pópis"] },
  { id: "friends", cat: "personagens", title: "Os 10 personagens mais lembrados de Friends", source: POP,
    items: ["Rachel", "Ross", "Joey", "Chandler", "Monica", "Phoebe", "Gunther", "Janice", "Mike", "Ursula"] },
  { id: "simpsons", cat: "personagens", title: "Os 10 personagens mais lembrados de Os Simpsons", source: POP,
    items: ["Homer", "Bart", "Marge", "Lisa", "Maggie", "Sr. Burns|Burns|Senhor Burns", "Ned Flanders|Flanders", "Moe", "Apu", "Milhouse"] },
  { id: "sitio", cat: "personagens", title: "Os 10 personagens mais lembrados do Sítio do Picapau Amarelo", source: POP,
    items: ["Emília", "Narizinho", "Pedrinho", "Dona Benta", "Tia Nastácia", "Visconde de Sabugosa|Visconde", "Cuca", "Saci", "Rabicó", "Tio Barnabé"] },
  { id: "turma-monica", cat: "personagens", title: "Os 10 personagens mais lembrados da Turma da Mônica", source: POP,
    items: ["Mônica", "Cebolinha", "Cascão", "Magali", "Chico Bento", "Bidu", "Franjinha", "Anjinho", "Penadinho", "Horácio"] },
  { id: "stranger-things", cat: "personagens", title: "Os 10 personagens mais lembrados de Stranger Things", source: POP,
    items: ["Eleven|Onze", "Mike", "Dustin", "Lucas", "Will", "Steve", "Max", "Hopper", "Joyce", "Nancy"] },
  { id: "bob-esponja", cat: "personagens", title: "Os 10 personagens mais lembrados de Bob Esponja", source: POP,
    items: ["Bob Esponja", "Patrick", "Lula Molusco", "Sr. Siriguejo|Siriguejo", "Sandy", "Plankton", "Gary", "Karen", "Sra. Puff|Senhora Puff", "Pérola"] },
  { id: "toy-story", cat: "personagens", title: "Os 10 personagens mais lembrados de Toy Story", source: POP,
    items: ["Woody", "Buzz Lightyear|Buzz", "Jessie", "Sr. Cabeça de Batata|Cabeça de Batata", "Rex", "Porquinho|Porco|Hamm", "Slinky", "Bala no Alvo", "Lotso", "Garfinho|Forky"] },
  { id: "hp-personagens", cat: "personagens", title: "Os 10 personagens mais lembrados de Harry Potter", source: POP,
    items: ["Harry Potter|Harry", "Hermione", "Rony|Ron", "Dumbledore", "Voldemort", "Hagrid", "Snape", "Draco Malfoy|Draco|Malfoy", "Sirius Black|Sirius", "Neville"] },
  { id: "sw-personagens", cat: "personagens", title: "Os 10 personagens mais lembrados de Star Wars", source: POP,
    items: ["Darth Vader|Vader", "Luke Skywalker|Luke", "Yoda", "Princesa Leia|Leia", "Han Solo", "Chewbacca|Chewie", "R2-D2", "C-3PO", "Obi-Wan Kenobi|Obi-Wan", "Palpatine|Imperador"] },
  { id: "shrek-personagens", cat: "personagens", title: "Os 10 personagens mais lembrados de Shrek", source: POP,
    items: ["Shrek", "Burro", "Fiona", "Gato de Botas", "Lord Farquaad|Farquaad", "Dragão|Dragoa", "Biscoito|Gingy", "Pinóquio", "Fada Madrinha", "Príncipe Encantado"] },
  { id: "rei-leao", cat: "personagens", title: "Os 10 personagens mais lembrados de O Rei Leão", source: POP,
    items: ["Simba", "Mufasa", "Scar", "Timão", "Pumba", "Nala", "Rafiki", "Zazu", "Sarabi", "Shenzi"] },
  { id: "frozen", cat: "personagens", title: "Os 10 personagens mais lembrados de Frozen", source: POP,
    items: ["Elsa", "Anna", "Olaf", "Kristoff", "Sven", "Hans", "Pabbie|Vovô Pabbie", "Marshmallow", "Oaken", "Duque de Weselton|Duque"] },
  { id: "nemo", cat: "personagens", title: "Os 10 personagens mais lembrados de Procurando Nemo", source: POP,
    items: ["Nemo", "Marlin", "Dory", "Crush", "Bruce", "Guelra|Gill", "Squirt", "Darla", "Nigel", "Sr. Raia|Raia"] },
  { id: "viloes-disney", cat: "personagens", title: "Os 10 vilões mais famosos da Disney", source: POP,
    items: ["Malévola", "Úrsula", "Scar", "Jafar", "Cruella", "Rainha Má", "Hades", "Capitão Gancho|Gancho", "Gaston", "Mamãe Gothel|Gothel"] },
  { id: "terror-personagens", cat: "personagens", title: "Os 10 personagens de terror mais famosos", source: POP,
    items: ["Freddy Krueger|Freddy", "Jason", "Chucky", "Pennywise|It", "Michael Myers", "Ghostface|Pânico", "Annabelle", "Samara", "Valak|A Freira", "Leatherface"] },
  { id: "gatos-famosos", cat: "personagens", title: "Os 10 gatos mais famosos da ficção", source: POP,
    items: ["Garfield", "Tom", "Frajola", "Gato de Botas", "Gato de Cheshire|Gato Risonho", "Gato Félix|Félix", "Mingau", "Hello Kitty", "Marie", "Salem"] },
  { id: "caes-famosos", cat: "personagens", title: "Os 10 cachorros mais famosos da ficção", source: POP,
    items: ["Scooby-Doo|Scooby", "Snoopy", "Pluto", "Bidu", "Beethoven", "Marley", "Lassie", "Pateta", "Bolt", "Dug"] },
  { id: "ratos-famosos", cat: "personagens", title: "Os 10 ratos mais famosos da ficção", source: POP,
    items: ["Mickey", "Jerry", "Minnie", "Ligeirinho|Speedy Gonzales", "Stuart Little", "Remy", "Pinky e Cérebro|Pinky|Cérebro", "Mestre Splinter|Splinter", "Fievel", "Bernardo e Bianca|Bernardo|Bianca"] },
  { id: "robos-famosos", cat: "personagens", title: "Os 10 robôs mais famosos da ficção", source: POP,
    items: ["R2-D2", "WALL·E|Wall-E|Walle", "C-3PO", "Exterminador do Futuro|Exterminador|T-800", "Optimus Prime", "Baymax", "Bumblebee", "RoboCop", "EVA", "Megatron"] },
  { id: "carros-famosos", cat: "personagens", title: "Os 10 carros mais famosos do cinema e da TV", source: POP,
    items: ["Relâmpago McQueen|McQueen", "Batmóvel", "DeLorean", "Herbie", "KITT|Super Máquina", "Mate", "Ecto-1", "Mach 5", "Fusca|Fusca do Herbie", "Bumblebee"] },
  { id: "disney-classicos", cat: "personagens", title: "Os 10 personagens clássicos da Disney mais famosos", source: POP,
    items: ["Mickey", "Pato Donald|Donald", "Minnie", "Pateta", "Pluto", "Margarida", "Tio Patinhas", "Zé Carioca", "Huguinho, Zezinho e Luisinho|Huguinho|Zezinho|Luisinho", "Ursinho Pooh|Pooh"] },

  // ───────────── TV ─────────────
  { id: "bbb-3", cat: "tv", title: "Os campeões do Big Brother Brasil do BBB16 ao BBB25", source: "TV Globo",
    items: ["Munik Nunes|Munik", "Emilly Araújo|Emilly", "Gleici Damasceno|Gleici", "Paula von Sperling|Paula", "Thelma Assis|Thelma", "Juliette", "Arthur Aguiar|Arthur", "Amanda Meirelles|Amanda", "Davi Brito|Davi", "Renata Saldanha|Renata"] },
  { id: "programas-infantis", cat: "tv", title: "Os 10 programas infantis mais marcantes da TV brasileira", source: POP,
    items: ["Castelo Rá-Tim-Bum", "Xou da Xuxa|Xuxa", "TV Colosso", "Sítio do Picapau Amarelo|Sítio", "Bom Dia & Cia", "TV Globinho", "Disney Cruj", "Mundo da Lua", "Teletubbies", "Cocoricó"] },
  { id: "series-famosas", cat: "tv", title: "As 10 séries mais famosas de todos os tempos", source: POP,
    items: ["Friends", "Breaking Bad", "Game of Thrones", "Stranger Things", "The Office", "La Casa de Papel", "Grey's Anatomy", "The Walking Dead", "Round 6|Squid Game", "Os Simpsons"] },

  // ───────────── Música ─────────────
  { id: "madonna", cat: "musica", title: "Os 10 primeiros álbuns de estúdio da Madonna", source: "Discografia oficial",
    items: ["Madonna", "Like a Virgin", "True Blue", "Like a Prayer", "Erotica", "Bedtime Stories", "Ray of Light", "Music", "American Life", "Confessions on a Dance Floor|Confessions"] },
  { id: "pink-floyd", cat: "musica", title: "Os 10 primeiros álbuns de estúdio do Pink Floyd", source: "Discografia oficial",
    items: ["The Piper at the Gates of Dawn|Piper at the Gates of Dawn", "A Saucerful of Secrets", "More", "Ummagumma", "Atom Heart Mother", "Meddle", "Obscured by Clouds", "The Dark Side of the Moon|Dark Side of the Moon", "Wish You Were Here", "Animals"] },
  { id: "rhcp", cat: "musica", title: "Os 10 primeiros álbuns do Red Hot Chili Peppers", source: "Discografia oficial",
    items: ["The Red Hot Chili Peppers|Red Hot Chili Peppers", "Freaky Styley", "The Uplift Mofo Party Plan|Uplift Mofo Party Plan", "Mother's Milk|Mothers Milk", "Blood Sugar Sex Magik", "One Hot Minute", "Californication", "By the Way", "Stadium Arcadium", "I'm with You|Im with You"] },
  { id: "foo-fighters", cat: "musica", title: "Os 10 primeiros álbuns do Foo Fighters", source: "Discografia oficial",
    items: ["Foo Fighters", "The Colour and the Shape|The Color and the Shape", "There Is Nothing Left to Lose", "One by One", "In Your Honor", "Echoes, Silence, Patience & Grace|Echoes Silence Patience and Grace", "Wasting Light", "Sonic Highways", "Concrete and Gold", "Medicine at Midnight"] },
  { id: "grammy-00", cat: "musica", title: "Álbuns vencedores do Grammy de Álbum do Ano (2000 a 2009)", source: "Recording Academy",
    items: ["Supernatural (Santana)|Supernatural", "Two Against Nature (Steely Dan)|Two Against Nature", "O Brother, Where Art Thou? (trilha sonora)|O Brother Where Art Thou", "Come Away with Me (Norah Jones)|Come Away with Me", "Speakerboxxx/The Love Below (OutKast)|Speakerboxxx|The Love Below", "Genius Loves Company (Ray Charles)|Genius Loves Company", "How to Dismantle an Atomic Bomb (U2)|How to Dismantle an Atomic Bomb", "Taking the Long Way (Dixie Chicks)|Taking the Long Way", "River: The Joni Letters (Herbie Hancock)|River The Joni Letters", "Raising Sand (Robert Plant e Alison Krauss)|Raising Sand"] },
  { id: "nevermind", cat: "musica", title: "As 10 primeiras faixas do álbum Nevermind, do Nirvana", source: "Nevermind (1991)",
    items: ["Smells Like Teen Spirit", "In Bloom", "Come as You Are", "Breed", "Lithium", "Polly", "Territorial Pissings", "Drain You", "Lounge Act", "Stay Away"] },
  { id: "back-in-black", cat: "musica", title: "As 10 faixas do álbum Back in Black, do AC/DC", source: "Back in Black (1980)",
    items: ["Hells Bells", "Shoot to Thrill", "What Do You Do for Money Honey", "Givin the Dog a Bone|Giving the Dog a Bone", "Let Me Put My Love into You", "Back in Black", "You Shook Me All Night Long", "Have a Drink on Me", "Shake a Leg", "Rock and Roll Ain't Noise Pollution|Rock and Roll Aint Noise Pollution"] },
  { id: "hybrid-theory", cat: "musica", title: "As 10 primeiras faixas do álbum Hybrid Theory, do Linkin Park", source: "Hybrid Theory (2000)",
    items: ["Papercut", "One Step Closer", "With You", "Points of Authority", "Crawling", "Runaway", "By Myself", "In the End", "A Place for My Head", "Forgotten"] },
  { id: "appetite", cat: "musica", title: "As 10 primeiras faixas do Appetite for Destruction, do Guns N' Roses", source: "Appetite for Destruction (1987)",
    items: ["Welcome to the Jungle", "It's So Easy|Its So Easy", "Nightrain", "Out ta Get Me", "Mr. Brownstone|Mr Brownstone", "Paradise City", "My Michelle", "Think About You", "Sweet Child o' Mine|Sweet Child of Mine", "You're Crazy|Youre Crazy"] },
  { id: "1989-faixas", cat: "musica", title: "As 10 primeiras faixas do álbum 1989, da Taylor Swift", source: "1989 (2014)",
    items: ["Welcome to New York", "Blank Space", "Style", "Out of the Woods", "All You Had to Do Was Stay", "Shake It Off", "I Wish You Would", "Bad Blood", "Wildest Dreams", "How You Get the Girl"] },
  { id: "bandas-rock", cat: "musica", title: "As 10 bandas de rock mais famosas", source: POP,
    items: ["The Beatles|Beatles", "Queen", "The Rolling Stones|Rolling Stones", "Led Zeppelin", "AC/DC|ACDC", "Nirvana", "Pink Floyd", "Guns N' Roses|Guns N Roses|Guns", "Metallica", "U2"] },
  { id: "mpb", cat: "musica", title: "Os 10 nomes mais famosos da MPB", source: POP,
    items: ["Caetano Veloso|Caetano", "Gilberto Gil|Gil", "Chico Buarque|Chico", "Elis Regina|Elis", "Tom Jobim", "Milton Nascimento|Milton", "Djavan", "Gal Costa|Gal", "Maria Bethânia|Bethânia", "Marisa Monte"] },
  { id: "instrumentos", cat: "musica", title: "Os 10 instrumentos musicais mais conhecidos", source: POP,
    items: ["Violão", "Piano", "Guitarra", "Bateria", "Flauta", "Violino", "Teclado", "Baixo|Contrabaixo", "Saxofone|Sax", "Pandeiro"] },
  { id: "pop-internacional", cat: "musica", title: "Os 10 cantores pop internacionais mais famosos", source: POP,
    items: ["Michael Jackson", "Madonna", "Beyoncé", "Taylor Swift", "Rihanna", "Lady Gaga", "Britney Spears", "Justin Bieber", "Bruno Mars", "Ariana Grande"] },
  { id: "beatles-musicas", cat: "musica", title: "As 10 músicas mais famosas dos Beatles", source: POP,
    items: ["Hey Jude", "Let It Be", "Yesterday", "Here Comes the Sun", "Come Together", "Help!", "Twist and Shout", "Something", "Yellow Submarine", "Strawberry Fields Forever"] },
  { id: "duplas-sertanejas", cat: "musica", title: "As 10 duplas sertanejas mais famosas", source: POP,
    items: ["Chitãozinho & Xororó|Chitãozinho e Xororó", "Zezé Di Camargo & Luciano|Zezé di Camargo e Luciano", "Jorge & Mateus|Jorge e Mateus", "Henrique & Juliano|Henrique e Juliano", "Bruno & Marrone|Bruno e Marrone", "Leandro & Leonardo|Leandro e Leonardo", "Maiara & Maraisa|Maiara e Maraisa", "Victor & Leo|Victor e Leo", "Zé Neto & Cristiano|Zé Neto e Cristiano", "Matheus & Kauan|Matheus e Kauan"] },

  // ───────────── Ciência ─────────────
  { id: "elementos-3", cat: "ciencia", title: "Os elementos de nº 21 a 30 da tabela periódica", source: "IUPAC",
    items: ["Escândio|Sc", "Titânio|Ti", "Vanádio|V", "Cromo|Cr", "Manganês|Mn", "Ferro|Fe", "Cobalto|Co", "Níquel|Ni", "Cobre|Cu", "Zinco|Zn"] },
  { id: "crosta", cat: "ciencia", title: "Os 10 elementos mais abundantes na crosta terrestre", source: "CRC Handbook of Chemistry and Physics",
    items: ["Oxigênio|O", "Silício|Si", "Alumínio|Al", "Ferro|Fe", "Cálcio|Ca", "Sódio|Na", "Magnésio|Mg", "Potássio|K", "Titânio|Ti", "Hidrogênio|H"] },
  { id: "prefixos-grandes", cat: "ciencia", title: "Os prefixos do SI do menor para o maior, de 10³ a 10³⁰", source: "BIPM (Sistema Internacional)",
    items: ["Quilo|Kilo", "Mega", "Giga", "Tera", "Peta", "Exa", "Zetta|Zeta", "Yotta|Iota|Yota", "Ronna", "Quetta|Queta"] },
  { id: "prefixos-pequenos", cat: "ciencia", title: "Os prefixos do SI do maior para o menor, de 10⁻³ a 10⁻³⁰", source: "BIPM (Sistema Internacional)",
    items: ["Mili", "Micro", "Nano", "Pico", "Femto", "Ato|Atto", "Zepto", "Yocto|Iocto", "Ronto", "Quecto"] },
  { id: "primeiros-no-espaco", cat: "ciencia", title: "As 10 primeiras pessoas a ir ao espaço", source: "NASA / Roscosmos",
    items: ["Yuri Gagarin|Gagarin", "Alan Shepard|Shepard", "Gus Grissom|Grissom", "Gherman Titov|Titov", "John Glenn|Glenn", "Scott Carpenter|Carpenter", "Andriyan Nikolayev|Nikolayev", "Pavel Popovich|Popovich", "Wally Schirra|Schirra", "Valery Bykovsky|Bykovsky"] },
  { id: "distancia-sol", cat: "ciencia", title: "Planetas e planetas anões em ordem de distância do Sol", source: "NASA / União Astronômica Internacional",
    items: ["Mercúrio", "Vênus", "Terra", "Marte", "Ceres", "Júpiter", "Saturno", "Urano", "Netuno", "Plutão"] },
  { id: "orgaos", cat: "ciencia", title: "Os 10 órgãos do corpo humano mais lembrados", source: POP,
    items: ["Coração", "Cérebro", "Pulmão|Pulmões", "Fígado", "Estômago", "Rim|Rins", "Intestino", "Pele", "Bexiga", "Pâncreas"] },
  { id: "constelacoes", cat: "ciencia", title: "As 10 constelações mais famosas", source: POP,
    items: ["Cruzeiro do Sul", "Órion|Orion|Três Marias", "Ursa Maior", "Escorpião", "Ursa Menor", "Cassiopeia", "Leão", "Touro", "Gêmeos", "Centauro"] },
  { id: "dinossauros", cat: "ciencia", title: "Os 10 dinossauros mais famosos", source: POP,
    items: ["Tiranossauro Rex|T-Rex|Tiranossauro", "Velociraptor", "Triceratops", "Estegossauro", "Braquiossauro", "Espinossauro", "Diplodoco", "Anquilossauro", "Parassaurolofo", "Pterodáctilo|Pteranodonte"] },

  // ───────────── Matemática ─────────────
  { id: "primos-2", cat: "matematica", title: "Os números primos do 11º ao 20º", source: "Matemática",
    items: ["31", "37", "41", "43", "47", "53", "59", "61", "67", "71"] },
  { id: "cubos", cat: "matematica", title: "Os 10 primeiros cubos perfeitos", source: "Matemática",
    items: ["1|um", "8|oito", "27", "64", "125", "216", "343", "512", "729", "1000|mil"] },
  { id: "fibonacci", cat: "matematica", title: "A sequência de Fibonacci (sem repetir o 1)", source: "Matemática",
    items: ["1|um", "2|dois", "3|três", "5|cinco", "8|oito", "13|treze", "21", "34", "55", "89"] },
  { id: "fatoriais", cat: "matematica", title: "Os fatoriais de 1! a 10!", source: "Matemática",
    items: ["1|um", "2|dois", "6|seis", "24", "120", "720", "5040", "40320", "362880", "3628800"] },
  { id: "romanos", cat: "matematica", title: "Os números de 1 a 10 em algarismos romanos", source: "Matemática",
    items: ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"] },
  { id: "poligonos", cat: "matematica", title: "Os polígonos de 3 a 12 lados", source: "Geometria",
    items: ["Triângulo", "Quadrilátero|Quadrado", "Pentágono", "Hexágono", "Heptágono", "Octógono", "Eneágono|Nonágono", "Decágono", "Undecágono|Hendecágono", "Dodecágono"] },
  { id: "tabuada-9", cat: "matematica", title: "A tabuada do 9", source: "Matemática",
    items: ["9|nove", "18|dezoito", "27", "36", "45", "54", "63", "72", "81", "90|noventa"] },

  // ───────────── História ─────────────
  { id: "presidentes-eua-4", cat: "historia", title: "Os presidentes dos EUA do 31º ao 40º", source: "Casa Branca",
    items: ["Herbert Hoover|Hoover", "Franklin D. Roosevelt|Roosevelt|FDR", "Harry Truman|Truman", "Dwight Eisenhower|Eisenhower", "John F. Kennedy|Kennedy|JFK", "Lyndon Johnson|Johnson", "Richard Nixon|Nixon", "Gerald Ford|Ford", "Jimmy Carter|Carter", "Ronald Reagan|Reagan"] },
  { id: "imperadores-romanos-2", cat: "historia", title: "Os imperadores romanos do 11º ao 20º", source: "História de Roma",
    items: ["Domiciano", "Nerva", "Trajano", "Adriano", "Antonino Pio", "Marco Aurélio", "Lúcio Vero", "Cômodo", "Pertinax", "Dídio Juliano"] },
  { id: "primeiros-ministros-uk", cat: "historia", title: "Os primeiros-ministros britânicos a partir de Margaret Thatcher", source: "Governo do Reino Unido",
    items: ["Margaret Thatcher|Thatcher", "John Major|Major", "Tony Blair|Blair", "Gordon Brown|Brown", "David Cameron|Cameron", "Theresa May|May", "Boris Johnson|Boris", "Liz Truss|Truss", "Rishi Sunak|Sunak", "Keir Starmer|Starmer"] },
  { id: "estados-eua-2", cat: "historia", title: "Os estados dos EUA do 11º ao 20º a entrar na União", source: "Arquivos Nacionais dos EUA",
    items: ["Nova York|New York", "Carolina do Norte|North Carolina", "Rhode Island", "Vermont", "Kentucky", "Tennessee", "Ohio", "Louisiana", "Indiana", "Mississippi"] },
  { id: "invencoes", cat: "historia", title: "10 grandes invenções em ordem cronológica", source: "Datas aproximadas mais citadas",
    items: ["Imprensa|Prensa", "Telescópio", "Máquina a vapor", "Pilha|Pilha elétrica|Bateria", "Fotografia|Câmera fotográfica", "Telefone", "Lâmpada|Lâmpada elétrica", "Automóvel|Carro", "Avião", "Televisão|TV"] },

  // ───────────── Geografia ─────────────
  { id: "paises-area-2", cat: "geografia", title: "Os maiores países do mundo em área, do 11º ao 20º", source: "ONU (área total)",
    items: ["República Democrática do Congo|RD Congo|Congo", "Arábia Saudita", "México", "Indonésia", "Sudão", "Líbia", "Irã", "Mongólia", "Peru", "Chade"] },
  { id: "menores-paises", cat: "geografia", title: "Os 10 menores países do mundo", source: "ONU (área total)",
    items: ["Vaticano", "Mônaco", "Nauru", "Tuvalu", "San Marino", "Liechtenstein", "Ilhas Marshall", "São Cristóvão e Névis", "Maldivas", "Malta"] },
  { id: "paises-populosos-2", cat: "geografia", title: "Os países mais populosos do mundo, do 11º ao 20º", source: "ONU, estimativas de 2023",
    items: ["Etiópia", "Japão", "Filipinas", "Egito", "República Democrática do Congo|RD Congo|Congo", "Vietnã", "Irã", "Turquia", "Alemanha", "Tailândia"] },
  { id: "oceania-pop", cat: "geografia", title: "Os 10 países mais populosos da Oceania", source: "ONU, estimativas de 2023",
    items: ["Austrália", "Papua-Nova Guiné", "Nova Zelândia", "Fiji", "Ilhas Salomão", "Vanuatu", "Samoa", "Kiribati", "Micronésia", "Tonga"] },
  { id: "africa-pop", cat: "geografia", title: "Os 10 países mais populosos da África", source: "ONU, estimativas de 2023",
    items: ["Nigéria", "Etiópia", "Egito", "República Democrática do Congo|RD Congo|Congo", "Tanzânia", "África do Sul", "Quênia", "Uganda", "Sudão", "Argélia"] },
  { id: "asia-pop", cat: "geografia", title: "Os 10 países mais populosos da Ásia (sem contar a Rússia)", source: "ONU, estimativas de 2023",
    items: ["Índia", "China", "Indonésia", "Paquistão", "Bangladesh", "Japão", "Filipinas", "Vietnã", "Irã", "Turquia"] },
  { id: "europa-pop", cat: "geografia", title: "Os 10 países mais populosos da Europa (sem contar a Rússia)", source: "ONU, estimativas de 2023",
    items: ["Alemanha", "Reino Unido", "França", "Itália", "Espanha", "Polônia", "Ucrânia", "Romênia", "Holanda|Países Baixos", "Bélgica"] },
  { id: "rios", cat: "geografia", title: "Os 10 rios mais longos do mundo", source: "Enciclopédia Britannica",
    items: ["Nilo", "Amazonas", "Yangtzé|Yangtze|Rio Azul", "Mississippi|Mississippi-Missouri", "Ienissei|Yenisei", "Rio Amarelo|Huang He", "Ob|Ob-Irtysh", "Paraná|Rio Paraná", "Congo|Rio Congo", "Amur"] },
  { id: "economias", cat: "geografia", title: "As 10 maiores economias do mundo (PIB)", source: "FMI, dados de 2024",
    items: ["Estados Unidos|EUA|USA", "China", "Alemanha", "Japão", "Índia", "Reino Unido", "França", "Itália", "Canadá", "Brasil"] },
  { id: "pontos-turisticos", cat: "geografia", title: "Os 10 pontos turísticos mais famosos do mundo", source: POP,
    items: ["Torre Eiffel", "Cristo Redentor", "Estátua da Liberdade", "Coliseu", "Muralha da China|Grande Muralha", "Pirâmides do Egito|Pirâmides de Gizé|Pirâmides", "Machu Picchu", "Big Ben", "Taj Mahal", "Torre de Pisa"] },

  // ───────────── Brasil ─────────────
  { id: "capitais-menos-populosas", cat: "brasil", title: "As 10 capitais brasileiras menos populosas", source: "IBGE, Censo 2022",
    items: ["Palmas", "Vitória", "Rio Branco", "Boa Vista", "Macapá", "Porto Velho", "Florianópolis|Floripa", "Aracaju", "Cuiabá", "Natal"] },
  { id: "municipios", cat: "brasil", title: "Os 10 estados com mais municípios", source: "IBGE",
    items: ["Minas Gerais|MG|Minas", "São Paulo|SP", "Rio Grande do Sul|RS", "Bahia|BA", "Paraná|PR", "Santa Catarina|SC", "Goiás|GO", "Piauí|PI", "Paraíba|PB", "Maranhão|MA"] },
  { id: "feriados", cat: "brasil", title: "Os feriados nacionais em ordem do calendário", source: "Leis federais",
    items: ["Ano Novo|Confraternização Universal", "Sexta-feira Santa|Paixão de Cristo|Sexta-feira da Paixão", "Tiradentes", "Dia do Trabalho|Dia do Trabalhador", "Independência|7 de Setembro", "Nossa Senhora Aparecida|Dia das Crianças|12 de Outubro", "Finados|Dia de Finados", "Proclamação da República", "Consciência Negra|Dia da Consciência Negra", "Natal"] },
  { id: "estados-alfabetica", cat: "brasil", title: "Os 10 primeiros estados em ordem alfabética (sem o DF)", source: "Ordem alfabética",
    items: ["Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso"] },
  { id: "capitais-alfabetica", cat: "brasil", title: "As 10 primeiras capitais em ordem alfabética", source: "Ordem alfabética",
    items: ["Aracaju", "Belém", "Belo Horizonte|BH", "Boa Vista", "Brasília", "Campo Grande", "Cuiabá", "Curitiba", "Florianópolis|Floripa", "Fortaleza"] },
  { id: "cidades-turisticas", cat: "brasil", title: "As 10 cidades mais turísticas do Brasil", source: POP,
    items: ["Rio de Janeiro|Rio", "Salvador", "Foz do Iguaçu", "Florianópolis|Floripa", "Gramado", "Fortaleza", "Fernando de Noronha|Noronha", "Bonito", "Porto Seguro", "São Paulo"] },
  { id: "hino-nacional", cat: "brasil", title: "As 10 primeiras palavras do Hino Nacional", source: "Hino Nacional Brasileiro",
    items: ["Ouviram", "do", "Ipiranga", "as", "margens", "plácidas", "de", "um", "povo", "heroico"] },

  // ───────────── Comida e bebida ─────────────
  { id: "frutas", cat: "comida", title: "As 10 frutas mais populares do Brasil", source: POP,
    items: ["Banana", "Maçã", "Laranja", "Uva", "Morango", "Melancia", "Abacaxi", "Manga", "Mamão", "Limão"] },
  { id: "pizza", cat: "comida", title: "Os 10 sabores de pizza mais pedidos", source: POP,
    items: ["Calabresa", "Mussarela|Muçarela|Queijo", "Portuguesa", "Frango com Catupiry|Frango", "Margherita|Marguerita", "Quatro Queijos|4 Queijos", "Pepperoni", "Napolitana", "Atum", "Palmito"] },
  { id: "sorvete", cat: "comida", title: "Os 10 sabores de sorvete mais pedidos", source: POP,
    items: ["Chocolate", "Morango", "Creme", "Flocos", "Baunilha", "Napolitano", "Limão", "Coco", "Pistache", "Menta|Hortelã"] },
  { id: "festa-junina", cat: "comida", title: "As 10 comidas de festa junina mais famosas", source: POP,
    items: ["Pipoca", "Pamonha", "Canjica|Mungunzá", "Paçoca", "Pé de moleque", "Quentão", "Milho cozido|Milho", "Bolo de milho", "Cuscuz", "Maçã do amor"] },
  { id: "salgados", cat: "comida", title: "Os 10 salgadinhos de festa mais famosos", source: POP,
    items: ["Coxinha", "Empada|Empadinha", "Quibe|Kibe", "Risole|Rissole", "Pastel|Pastelzinho", "Enroladinho de salsicha|Enroladinho", "Bolinha de queijo", "Esfiha|Esfirra", "Croquete", "Pão de queijo"] },
  { id: "doces-festa", cat: "comida", title: "Os 10 docinhos de festa mais famosos", source: POP,
    items: ["Brigadeiro", "Beijinho", "Cajuzinho", "Bicho de pé", "Olho de sogra", "Casadinho|Bem-casado", "Brigadeiro branco", "Bombom", "Quindim", "Trufa"] },
  { id: "bebidas", cat: "comida", title: "As 10 bebidas mais consumidas no Brasil", source: POP,
    items: ["Água", "Café", "Refrigerante", "Suco", "Cerveja", "Leite", "Chá", "Vinho", "Água de coco", "Energético"] },
  { id: "cafe-da-manha", cat: "comida", title: "As 10 coisas mais comuns no café da manhã", source: POP,
    items: ["Pão|Pão francês", "Café", "Leite", "Manteiga", "Queijo", "Presunto", "Ovo|Ovos", "Fruta|Frutas", "Cereal|Sucrilhos", "Tapioca"] },
  { id: "fast-food", cat: "comida", title: "As 10 redes de fast food mais famosas no Brasil", source: POP,
    items: ["McDonald's|McDonalds|Mc", "Burger King|BK", "Subway", "KFC", "Bob's|Bobs", "Habib's|Habibs", "Pizza Hut", "Domino's|Dominos", "Giraffas", "Spoleto"] },
  { id: "refrigerantes", cat: "comida", title: "Os 10 refrigerantes mais famosos do Brasil", source: POP,
    items: ["Coca-Cola|Coca", "Guaraná Antarctica|Guaraná", "Fanta", "Pepsi", "Sprite", "Kuat", "Sukita", "Schweppes", "Soda|Soda Antarctica", "Dolly"] },
  { id: "comida-japonesa", cat: "comida", title: "Os 10 pratos de comida japonesa mais pedidos", source: POP,
    items: ["Sushi", "Sashimi", "Temaki", "Hot roll|Hot", "Yakisoba", "Lámen|Ramen", "Guioza|Gyoza", "Tempurá|Tempura", "Missoshiru", "Uramaki"] },
  { id: "comida-italiana", cat: "comida", title: "Os 10 pratos italianos mais famosos", source: POP,
    items: ["Pizza", "Lasanha", "Espaguete|Macarrão", "Risoto", "Nhoque", "Ravióli", "Carbonara", "Tiramisù|Tiramisu", "Bruschetta", "Polenta"] },
  { id: "salada", cat: "comida", title: "Os 10 ingredientes mais comuns na salada", source: POP,
    items: ["Alface", "Tomate", "Cebola", "Cenoura", "Pepino", "Rúcula", "Beterraba", "Repolho", "Palmito", "Agrião"] },
  { id: "comidas-tipicas", cat: "comida", title: "As 10 comidas típicas brasileiras mais famosas", source: POP,
    items: ["Feijoada", "Churrasco", "Pão de queijo", "Coxinha", "Brigadeiro", "Açaí", "Acarajé", "Moqueca", "Tapioca", "Pastel"] },
  { id: "chocolates", cat: "comida", title: "As 10 marcas de chocolate mais famosas no Brasil", source: POP,
    items: ["Lacta", "Nestlé", "Garoto", "Cacau Show", "Kopenhagen", "Hershey's|Hersheys", "Ferrero Rocher|Ferrero", "Lindt", "Kinder", "Milka"] },
  { id: "churrasco", cat: "comida", title: "As 10 carnes mais pedidas no churrasco", source: POP,
    items: ["Picanha", "Linguiça", "Fraldinha", "Costela", "Maminha", "Alcatra", "Coração de frango|Coraçãozinho", "Asinha de frango|Asa de frango|Asinha", "Cupim", "Contrafilé"] },

  // ───────────── Animais ─────────────
  { id: "animais-fazenda", cat: "animais", title: "Os 10 animais de fazenda mais lembrados", source: POP,
    items: ["Vaca|Boi", "Galinha|Galo", "Porco", "Cavalo", "Ovelha|Carneiro", "Cabra|Bode", "Pato", "Burro|Jumento", "Coelho", "Peru"] },
  { id: "animais-savana", cat: "animais", title: "Os 10 animais da savana africana mais lembrados", source: POP,
    items: ["Leão", "Elefante", "Girafa", "Zebra", "Hipopótamo", "Rinoceronte", "Leopardo", "Guepardo|Chita", "Hiena", "Gnu"] },
  { id: "animais-mar", cat: "animais", title: "Os 10 animais marinhos mais lembrados", source: POP,
    items: ["Tubarão", "Baleia", "Golfinho", "Polvo", "Água-viva", "Tartaruga marinha|Tartaruga", "Peixe-palhaço", "Cavalo-marinho", "Estrela-do-mar", "Lula"] },
  { id: "fauna-brasil", cat: "animais", title: "Os 10 animais mais famosos da fauna brasileira", source: POP,
    items: ["Onça-pintada|Onça", "Arara", "Tucano", "Mico-leão-dourado|Mico-leão", "Capivara", "Jacaré", "Bicho-preguiça|Preguiça", "Tamanduá", "Lobo-guará", "Boto-cor-de-rosa|Boto"] },
  { id: "pets", cat: "animais", title: "Os 10 animais de estimação mais comuns", source: POP,
    items: ["Cachorro|Cão", "Gato", "Peixe", "Pássaro|Passarinho", "Hamster", "Coelho", "Tartaruga|Jabuti", "Papagaio", "Porquinho-da-índia", "Calopsita"] },
  { id: "insetos", cat: "animais", title: "Os 10 insetos mais lembrados", source: POP,
    items: ["Formiga", "Mosca", "Abelha", "Mosquito|Pernilongo", "Borboleta", "Barata", "Joaninha", "Grilo", "Gafanhoto", "Besouro"] },
  { id: "animais-letais", cat: "animais", title: "Os animais que mais matam pessoas por ano", source: "Gates Notes, 2014",
    items: ["Mosquito", "Ser humano|Humano|Homem", "Cobra", "Cachorro|Cão", "Mosca tsé-tsé|Tsé-tsé", "Barbeiro", "Caramujo|Caramujo de água doce", "Lombriga", "Tênia|Solitária", "Crocodilo"] },
  { id: "aves-brasil", cat: "animais", title: "As 10 aves brasileiras mais conhecidas", source: POP,
    items: ["Bem-te-vi", "Sabiá", "Beija-flor", "Tucano", "Arara", "Papagaio", "João-de-barro", "Canário", "Pardal", "Coruja"] },

  // ───────────── Dia a dia ─────────────
  { id: "profissoes", cat: "diaadia", title: "As 10 profissões mais lembradas", source: POP,
    items: ["Médico|Médica", "Professor|Professora", "Policial", "Bombeiro|Bombeira", "Advogado|Advogada", "Engenheiro|Engenheira", "Dentista", "Enfermeiro|Enfermeira", "Cozinheiro|Cozinheira|Chef", "Motorista"] },
  { id: "materias", cat: "diaadia", title: "As 10 matérias da escola mais lembradas", source: POP,
    items: ["Matemática", "Português", "História", "Geografia", "Ciências", "Inglês", "Educação Física", "Artes", "Física", "Química"] },
  { id: "material-escolar", cat: "diaadia", title: "Os 10 itens de material escolar mais comuns", source: POP,
    items: ["Lápis", "Caneta", "Borracha", "Caderno", "Apontador", "Régua", "Mochila", "Estojo", "Cola", "Tesoura"] },
  { id: "praia", cat: "diaadia", title: "As 10 coisas que todo mundo leva para a praia", source: POP,
    items: ["Protetor solar", "Guarda-sol", "Toalha|Canga", "Cadeira", "Óculos de sol|Óculos escuros", "Chinelo", "Biquíni|Sunga|Roupa de banho", "Isopor|Cooler", "Boné|Chapéu", "Boia"] },
  { id: "banheiro", cat: "diaadia", title: "As 10 coisas que todo banheiro tem", source: POP,
    items: ["Papel higiênico", "Sabonete", "Escova de dente", "Pasta de dente|Creme dental", "Xampu|Shampoo", "Toalha", "Espelho", "Desodorante", "Condicionador", "Fio dental"] },
  { id: "cozinha", cat: "diaadia", title: "As 10 coisas que toda cozinha tem", source: POP,
    items: ["Geladeira", "Fogão", "Panela", "Prato", "Copo", "Garfo", "Faca", "Colher", "Pia", "Micro-ondas|Microondas"] },
  { id: "transportes", cat: "diaadia", title: "Os 10 meios de transporte mais lembrados", source: POP,
    items: ["Carro", "Ônibus", "Moto", "Bicicleta|Bike", "Avião", "Metrô", "Trem", "Barco|Navio", "Caminhão", "Helicóptero"] },
  { id: "roupas", cat: "diaadia", title: "As 10 peças de roupa mais comuns", source: POP,
    items: ["Camiseta|Blusa", "Calça", "Bermuda|Short", "Meia", "Cueca|Calcinha", "Tênis", "Casaco|Jaqueta", "Vestido", "Saia", "Moletom"] },
  { id: "brincadeiras", cat: "diaadia", title: "As 10 brincadeiras de infância mais clássicas", source: POP,
    items: ["Pega-pega", "Esconde-esconde", "Amarelinha", "Pular corda", "Queimada", "Pipa|Papagaio", "Bolinha de gude", "Polícia e ladrão", "Estátua", "Passa anel"] },
  { id: "natal", cat: "diaadia", title: "As 10 coisas que mais lembram o Natal", source: POP,
    items: ["Papai Noel", "Árvore de Natal|Árvore", "Presente|Presentes", "Panetone", "Peru|Chester", "Pisca-pisca", "Rena|Renas", "Presépio", "Ceia", "Amigo secreto"] },
  { id: "jogos-tabuleiro", cat: "diaadia", title: "Os 10 jogos de mesa mais famosos", source: POP,
    items: ["Xadrez", "Dama|Damas", "Uno", "Banco Imobiliário", "Dominó", "Jogo da Vida", "War", "Detetive", "Ludo", "Truco"] },
  { id: "medos", cat: "diaadia", title: "Os 10 medos mais comuns", source: POP,
    items: ["Altura", "Aranha", "Barata", "Cobra", "Escuro", "Falar em público", "Avião|Voar", "Palhaço", "Agulha|Injeção", "Morte"] },
  { id: "superpoderes", cat: "diaadia", title: "Os 10 superpoderes que todo mundo queria ter", source: POP,
    items: ["Voar", "Teletransporte|Teletransportar", "Invisibilidade|Ficar invisível", "Ler mentes|Telepatia", "Viajar no tempo", "Superforça", "Supervelocidade", "Imortalidade", "Controlar o tempo|Parar o tempo", "Cura|Se curar"] },
  { id: "apps", cat: "diaadia", title: "Os 10 aplicativos mais usados no Brasil", source: POP,
    items: ["WhatsApp|Zap", "Instagram|Insta", "YouTube", "TikTok", "Facebook", "Google", "Netflix", "Spotify", "Uber", "iFood"] },
  { id: "objetos-perdidos", cat: "diaadia", title: "Os 10 objetos que todo mundo vive perdendo", source: POP,
    items: ["Chave|Chaves", "Celular", "Controle remoto|Controle", "Óculos", "Carregador", "Guarda-chuva", "Caneta", "Carteira", "Fone de ouvido|Fone", "Meia"] },
  { id: "geladeira", cat: "diaadia", title: "As 10 coisas que nunca faltam na geladeira", source: POP,
    items: ["Água", "Leite", "Ovo|Ovos", "Manteiga|Margarina", "Queijo", "Refrigerante", "Fruta|Frutas", "Iogurte", "Presunto", "Pote de sorvete com feijão|Feijão"] },
  { id: "aniversario", cat: "diaadia", title: "As 10 coisas que toda festa de aniversário tem", source: POP,
    items: ["Bolo", "Brigadeiro", "Balão|Bexiga", "Vela", "Parabéns|Parabéns pra você", "Presente", "Salgadinho|Salgado", "Refrigerante", "Docinho|Doces", "Chapéu de festa|Chapeuzinho"] },
  { id: "partes-corpo", cat: "diaadia", title: "As 10 partes do corpo mais lembradas", source: POP,
    items: ["Cabeça", "Mão", "Pé", "Braço", "Perna", "Olho", "Boca", "Nariz", "Orelha", "Barriga"] },

  // ───────────── Frases do dia a dia ─────────────
  { id: "frases-crianca", cat: "frases", title: "Frases que toda criança diz", source: POP,
    items: ["Já chegamos?|~chegamos|~ja chegou", "Não fui eu!|~fui eu", "Tô com fome|~fome", "Só mais cinco minutinhos|~minutinho|~minutinhos|~cinco minutos|~5 minutos", "Mas por quê?|~por que|~porque", "Foi ele que começou|~comecou", "Compra pra mim?|~compra", "Tô entediado|~entediado|~entediada|~nada pra fazer|~tedio", "Não tô com sono|~sono", "Posso dormir na casa do meu amigo?|~dormir na casa"] },
  { id: "frases-chefe", cat: "frases", title: "Frases que todo chefe diz", source: POP,
    items: ["Precisamos alinhar|~alinhar|~alinhamento", "É pra ontem|~ontem", "Tem um minutinho?|~minutinho", "Vamos marcar uma reunião|~reuniao", "Somos uma família|~familia", "Pensa fora da caixa|~fora da caixa|~caixa", "Me manda por e-mail|~email|~e mail", "Vamos vestir a camisa|~camisa", "Preciso de um feedback|~feedback", "Já é sexta, mas...|~sexta"] },
  { id: "desculpas-academia", cat: "frases", title: "Desculpas para não ir à academia", source: POP,
    items: ["Tô cansado|~cansado|~cansada|~cansaco", "Segunda eu começo|~segunda", "Tá chovendo|~chuva|~chovendo", "Tô sem tempo|~tempo", "Tô dolorido do treino|~dolorido|~dor", "Tá frio|~frio", "Comi demais|~comi", "Amanhã eu vou|~amanha", "Esqueci a roupa|~roupa", "Hoje é feriado|~feriado"] },
  { id: "girias", cat: "frases", title: "As 10 gírias brasileiras mais usadas", source: POP,
    items: ["Mano|Mana|Mina", "Top", "Da hora|Dahora", "Massa", "Suave|De boa", "Partiu", "Sextou", "Treta", "Bagulho", "Cringe"] },
  { id: "frases-gamer", cat: "frases", title: "Frases de quem joga online", source: POP,
    items: ["Tá lagando|~lag|~lagando|~lagou", "Só mais uma partida|~mais uma", "GG|~gg", "Foi mal|~foi mal", "Noob|~noob|~nub", "Tá de hack|~hack|~hacker", "Me revive|~revive|~reviver", "Minha internet caiu|~internet|~caiu", "Tô sem bala|~bala|~municao", "Carrega o time|~carrega|~carregar"] },
  { id: "frases-atrasado", cat: "frases", title: "Mensagens de quem está atrasado", source: POP,
    items: ["Tô chegando|~chegando", "Tô saindo|~saindo", "Cinco minutinhos|~minutinho|~minutinhos|~cinco minutos|~5 minutos", "Tô no trânsito|~transito", "Tô quase pronto|~pronto|~pronta", "Tô no banho|~banho", "Já tô na esquina|~esquina", "Me espera aí|~espera", "Pode ir pedindo|~pedindo|~pedir", "Tô procurando vaga|~vaga"] },

  // ───────────── Curiosidades ─────────────
  { id: "letras-portugues", cat: "curiosidades", title: "As 10 letras mais usadas na língua portuguesa", source: "Frequência de letras em textos em português",
    items: ["A", "E", "O", "S", "R", "I", "N", "D", "M", "U"] },
  { id: "sobrenomes", cat: "curiosidades", title: "Os 10 sobrenomes mais comuns do Brasil", source: "Levantamentos de registros civis",
    items: ["Silva", "Santos", "Oliveira", "Souza|Sousa", "Rodrigues", "Ferreira", "Alves", "Pereira", "Lima", "Gomes"] },
  { id: "nomes", cat: "curiosidades", title: "Os 10 nomes mais comuns do Brasil", source: "IBGE, Censo 2010",
    items: ["Maria", "José", "Ana", "João", "Antônio", "Francisco", "Carlos", "Paulo", "Pedro", "Lucas"] },
  { id: "idiomas-mundo", cat: "curiosidades", title: "Os 10 idiomas mais falados do mundo", source: "Ethnologue, 2023 (falantes totais)",
    items: ["Inglês", "Mandarim|Chinês", "Hindi", "Espanhol", "Francês", "Árabe", "Bengali", "Português", "Russo", "Urdu"] },

  // ───────────── Idiomas ─────────────
  { id: "numeros-frances", cat: "idiomas", title: "Os números de 1 a 10 em francês", source: "Francês",
    items: ["Un", "Deux", "Trois", "Quatre", "Cinq", "Six", "Sept", "Huit", "Neuf", "Dix"] },
  { id: "numeros-italiano", cat: "idiomas", title: "Os números de 1 a 10 em italiano", source: "Italiano",
    items: ["Uno", "Due", "Tre", "Quattro", "Cinque", "Sei", "Sette", "Otto", "Nove", "Dieci"] },
  { id: "numeros-alemao", cat: "idiomas", title: "Os números de 1 a 10 em alemão", source: "Alemão",
    items: ["Eins", "Zwei", "Drei", "Vier", "Fünf|Funf|Fuenf", "Sechs", "Sieben", "Acht", "Neun", "Zehn"] },
  { id: "cores-ingles", cat: "idiomas", title: "As 10 cores mais básicas em inglês", source: POP,
    items: ["Red", "Blue", "Green", "Yellow", "Black", "White", "Orange", "Pink", "Purple", "Brown"] },
  { id: "animais-ingles", cat: "idiomas", title: "Os 10 animais mais básicos em inglês", source: POP,
    items: ["Dog", "Cat", "Bird", "Fish", "Horse", "Cow", "Lion", "Elephant", "Monkey", "Rabbit"] },
  { id: "ola-idiomas", cat: "idiomas", title: "Como se diz \"olá\" nos idiomas mais falados", source: POP,
    items: ["Hello (inglês)|Hello|Hi", "Hola (espanhol)|Hola", "Bonjour (francês)|Bonjour", "Ciao (italiano)|Ciao", "Hallo (alemão)|Hallo", "Konnichiwa (japonês)|Konnichiwa", "Ni hao (mandarim)|Ni hao|Nihao", "Annyeong (coreano)|Annyeong|Annyeonghaseyo", "Privet (russo)|Privet", "Namastê (hindi)|Namaste|Namastê"] },
);
