// Listas do jogo. Para adicionar uma nova, copie um bloco e preencha:
// - title: o desafio mostrado ao jogador
// - source: de onde vieram os dados
// - items: exatamente 10, em ordem; "aliases" são outras grafias aceitas
const LISTS = [
  {
    id: "estados-populosos",
    title: "Os 10 estados brasileiros mais populosos",
    source: "IBGE, Censo 2022",
    items: [
      { name: "São Paulo", aliases: ["SP"] },
      { name: "Minas Gerais", aliases: ["MG", "Minas"] },
      { name: "Rio de Janeiro", aliases: ["RJ", "Rio"] },
      { name: "Bahia", aliases: ["BA"] },
      { name: "Paraná", aliases: ["PR"] },
      { name: "Rio Grande do Sul", aliases: ["RS"] },
      { name: "Pernambuco", aliases: ["PE"] },
      { name: "Ceará", aliases: ["CE"] },
      { name: "Pará", aliases: ["PA"] },
      { name: "Santa Catarina", aliases: ["SC"] },
    ],
  },
  {
    id: "estados-area",
    title: "Os 10 maiores estados brasileiros em área",
    source: "IBGE",
    items: [
      { name: "Amazonas", aliases: ["AM"] },
      { name: "Pará", aliases: ["PA"] },
      { name: "Mato Grosso", aliases: ["MT"] },
      { name: "Minas Gerais", aliases: ["MG", "Minas"] },
      { name: "Bahia", aliases: ["BA"] },
      { name: "Mato Grosso do Sul", aliases: ["MS"] },
      { name: "Goiás", aliases: ["GO"] },
      { name: "Maranhão", aliases: ["MA"] },
      { name: "Rio Grande do Sul", aliases: ["RS"] },
      { name: "Tocantins", aliases: ["TO"] },
    ],
  },
  {
    id: "capitais-populosas",
    title: "As 10 capitais brasileiras mais populosas",
    source: "IBGE, Censo 2022",
    items: [
      { name: "São Paulo", aliases: ["SP", "Sampa"] },
      { name: "Rio de Janeiro", aliases: ["Rio", "RJ"] },
      { name: "Brasília", aliases: ["DF", "Distrito Federal"] },
      { name: "Fortaleza", aliases: [] },
      { name: "Salvador", aliases: [] },
      { name: "Belo Horizonte", aliases: ["BH"] },
      { name: "Manaus", aliases: [] },
      { name: "Curitiba", aliases: [] },
      { name: "Recife", aliases: [] },
      { name: "Goiânia", aliases: [] },
    ],
  },
  {
    id: "paises-area",
    title: "Os 10 maiores países do mundo em área",
    source: "ONU / CIA World Factbook (área total)",
    items: [
      { name: "Rússia", aliases: ["Russia"] },
      { name: "Canadá", aliases: [] },
      { name: "Estados Unidos", aliases: ["EUA", "USA", "Estados Unidos da América"] },
      { name: "China", aliases: [] },
      { name: "Brasil", aliases: [] },
      { name: "Austrália", aliases: [] },
      { name: "Índia", aliases: [] },
      { name: "Argentina", aliases: [] },
      { name: "Cazaquistão", aliases: ["Casaquistão"] },
      { name: "Argélia", aliases: [] },
    ],
  },
  {
    id: "montanhas",
    title: "As 10 montanhas mais altas do mundo",
    source: "Altitudes oficiais dos picos de 8.000 m",
    items: [
      { name: "Everest", aliases: ["Monte Everest"] },
      { name: "K2", aliases: [] },
      { name: "Kangchenjunga", aliases: ["Kanchenjunga"] },
      { name: "Lhotse", aliases: [] },
      { name: "Makalu", aliases: [] },
      { name: "Cho Oyu", aliases: [] },
      { name: "Dhaulagiri", aliases: [] },
      { name: "Manaslu", aliases: [] },
      { name: "Nanga Parbat", aliases: [] },
      { name: "Annapurna", aliases: [] },
    ],
  },
];
