// Todos os textos do site em [português, inglês, espanhol]. Ver js/i18n.js.
// "¦" separa singular e plural; {nome} é trocado pelo valor na hora.

const TEXTS = {};

// ───────────── navegação e página inicial ─────────────
Object.assign(TEXTS, {
  "nav.home": ["Início", "Home", "Inicio"],
  "nav.lang": ["Idioma", "Language", "Idioma"],
  "nav.profile": ["Perfil", "Profile", "Perfil"],
  "nav.back": ["Voltar para o Gamezi", "Back to Gamezi", "Volver a Gamezi"],
  "nav.settings": ["Configurações", "Settings", "Ajustes"],
  "nav.theme": ["Tema", "Theme", "Tema"],
  "nav.sound": ["Som", "Sound", "Sonido"],
  "home.tag": ["Adivinhe os itens da lista. O óbvio vale 1, o difícil vale 10.", "Guess the items on the list. The obvious is worth 1, the hard one 10.", "Adivina los ítems de la lista. Lo obvio vale 1, lo difícil 10."],
  "home.free": ["Partida livre", "Free play", "Partida libre"],
  "home.freeSub": ["De 1 a 8 jogadores no mesmo celular", "1 to 8 players on one phone", "De 1 a 8 jugadores en el mismo celular"],
  "home.online": ["Online", "Online", "Online"],
  "home.onlineSub": ["Cada um no seu celular", "Everyone on their own phone", "Cada uno en su celular"],
  "home.more": ["Mais jogos", "More games", "Más juegos"],
  "account.short": ["Entrar", "Sign in", "Entrar"],
  "nav.profileOpen": ["Abrir perfil", "Open profile", "Abrir perfil"],
  "nav.themeDark": ["Usar modo escuro", "Switch to dark mode", "Usar modo oscuro"],
  "nav.themeLight": ["Usar modo claro", "Switch to light mode", "Usar modo claro"],
  "nav.soundOn": ["Som ligado (toque para desligar)", "Sound on (tap to mute)", "Sonido activado (toca para silenciar)"],
  "nav.soundOff": ["Som desligado (toque para ligar)", "Sound off (tap to unmute)", "Sonido desactivado (toca para activar)"],
  "btn.play": ["Jogar", "Play", "Jugar"],
  "btn.online": ["Jogar online", "Play online", "Jugar online"],
  "btn.random": ["Sortear", "Random", "Al azar"],
  "btn.cancel": ["Cancelar", "Cancel", "Cancelar"],
  "btn.close": ["Fechar", "Close", "Cerrar"],
  "btn.backHome": ["Voltar ao início", "Back to home", "Volver al inicio"],
  "btn.chooseList": ["Escolher a lista", "Choose the list", "Elegir la lista"],
  "btn.createList": ["Criar lista", "Create list", "Crear lista"],
  "reveal.skip": ["toque para pular", "tap to skip", "toca para saltar"],
  "copied": ["Copiado!", "Copied!", "¡Copiado!"],
  "copyPrompt": ["Copie:", "Copy:", "Copia:"],
});

// ───────────── modos ─────────────
Object.assign(TEXTS, {
  "modes.title": ["Escolha o modo", "Choose a mode", "Elige el modo"],
  "mode.top10.short": ["Listas de 10 itens", "Lists of 10 items", "Listas de 10 ítems"],
  "mode.top30.short": ["Listas de 30 itens", "Lists of 30 items", "Listas de 30 ítems"],
  "mode.top50.short": ["Listas de 50 itens", "Lists of 50 items", "Listas de 50 ítems"],
  "mode.equipe.short": ["Todos juntos contra a lista", "Everyone together against the list", "Todos juntos contra la lista"],
  "mode.times.short": ["Time Vermelho contra Time Preto", "Red Team vs. Black Team", "Equipo Rojo contra Equipo Negro"],
  "mode.morte.name": ["Morte súbita", "Sudden death", "Muerte súbita"],
  "mode.morte.short": ["Errou, está fora", "One miss and you're out", "Fallaste, estás fuera"],
  "mode.equipe.name": ["Equipe contra a lista", "Team vs. the list", "Equipo contra la lista"],
  "mode.times.name": ["Times", "Teams", "Equipos"],
  "mode.lists": ["{n} lista¦{n} listas", "{n} list¦{n} lists", "{n} lista¦{n} listas"],
  "mode.change": ["Trocar modo", "Change mode", "Cambiar modo"],
  "mode.backRoom": ["Voltar à sala", "Back to the room", "Volver a la sala"],
  "mode.pickTag": ["sala online", "online room", "sala online"],
  "mode.suggestTag": ["toque numa lista para sugerir", "tap a list to suggest it", "toca una lista para sugerirla"],
  "team.0": ["Time Vermelho", "Red Team", "Equipo Rojo"],
  "team.1": ["Time Preto", "Black Team", "Equipo Negro"],
});

// ───────────── jogadores ─────────────
Object.assign(TEXTS, {
  "players.howMany": ["Quantos jogadores?", "How many players?", "¿Cuántos jugadores?"],
  "players.team": ["Quem joga na equipe?", "Who's on the team?", "¿Quién juega en el equipo?"],
  "players.teams": ["Monte os times", "Set up the teams", "Arma los equipos"],
  "players.player": ["Jogador {n}", "Player {n}", "Jugador {n}"],
  "players.count": ["{n} jog.", "{n} pl.", "{n} jug."],
  "players.nickPh": ["Seu nickname", "Your nickname", "Tu apodo"],
  "players.skinCustom": ["Skin personalizada", "Custom skin", "Skin personalizada"],
  "players.skinOf": ["Trocar skin do jogador {n}", "Change player {n}'s skin", "Cambiar la skin del jugador {n}"],
  "players.n": ["{n} jogador¦{n} jogadores", "{n} player¦{n} players", "{n} jugador¦{n} jugadores"],
  "label.solo": ["Modo solo: tente fazer o máximo de pontos.", "Solo mode: score as many points as you can.", "Modo solo: haz la mayor cantidad de puntos."],
  "label.1v1": ["Modo 1v1: um contra o outro.", "1v1 mode: head to head.", "Modo 1v1: uno contra el otro."],
  "label.ffa": ["Todos contra todos: {n} jogadores.", "Free-for-all: {n} players.", "Todos contra todos: {n} jugadores."],
  "label.teamSolo": ["Só você contra a lista.", "Just you against the list.", "Solo tú contra la lista."],
  "label.team": ["Equipe de {n}: todos juntos contra a lista, revezando a vez.", "Team of {n}: everyone against the list, taking turns.", "Equipo de {n}: todos juntos contra la lista, por turnos."],
  "label.teamsEmpty": ["Cada time precisa de pelo menos um jogador. Toque no time de alguém para trocar.", "Each team needs at least one player. Tap someone's team to switch it.", "Cada equipo necesita al menos un jugador. Toca el equipo de alguien para cambiarlo."],
  "label.teamsTap": ["Toque no time de alguém para trocar.", "Tap someone's team to switch it.", "Toca el equipo de alguien para cambiarlo."],
  "opt.sudden": ["Morte súbita: cada um tem uma vida só. Errou (ou o tempo acabou), está fora; os outros continuam.", "Sudden death: everyone has a single life. Miss (or run out of time) and you're out; the others keep going.", "Muerte súbita: cada uno tiene una sola vida. Si fallas (o se acaba el tiempo), quedas fuera; los demás siguen."],
  "opt.oneLife": ["1 vida", "1 life", "1 vida"],
  "opt.more": ["Mais opções", "More options", "Más opciones"],
  "start.who": ["Quem começa", "Who goes first", "Quién empieza"],
  "start.random": ["Sortear", "Random", "Sortear"],
  "start.drawn": ["Sorteio: {name} começa!", "Random draw: {name} goes first!", "Sorteo: ¡{name} empieza!"],
  "opt.timer": ["Tempo por vez", "Time per turn", "Tiempo por turno"],
  "opt.seconds": ["{n} segundos", "{n} seconds", "{n} segundos"],
  "opt.noLimit": ["Sem limite", "No limit", "Sin límite"],
  "opt.timerHelp": ["Modo relâmpago: quem não chutar em {n} segundos perde a vez.", "Lightning mode: whoever doesn't guess within {n} seconds loses their turn.", "Modo relámpago: quien no responda en {n} segundos pierde el turno."],
  "opt.timerHelpLives": ["Modo relâmpago: quem não chutar em {n} segundos perde a vez e uma vida.", "Lightning mode: whoever doesn't guess within {n} seconds loses their turn and a life.", "Modo relámpago: quien no responda en {n} segundos pierde el turno y una vida."],
  "opt.timerOff": ["Cada um pensa o tempo que quiser.", "Everyone can take as long as they like.", "Cada uno piensa el tiempo que quiera."],
  "opt.lives": ["Vidas", "Lives", "Vidas"],
  "opt.noLives": ["Sem vidas", "No lives", "Sin vidas"],
  "opt.withLives": ["Com vidas", "With lives", "Con vidas"],
  "opt.livesCounts": ["{a} no Top 10, {b} no Top 30, {c} no Top 50", "{a} in Top 10, {b} in Top 30, {c} in Top 50", "{a} en el Top 10, {b} en el Top 30, {c} en el Top 50"],
  "opt.livesTeam": ["A equipe divide as vidas ({counts}). Cada erro custa uma, e dá para trocar uma vida por uma dica.", "The team shares the lives ({counts}). Each miss costs one, and you can trade a life for a hint.", "El equipo comparte las vidas ({counts}). Cada error cuesta una, y puedes cambiar una vida por una pista."],
  "opt.livesOwn": ["Cada jogador tem as próprias vidas ({counts}). Quem zera fica de fora e os outros continuam.", "Each player has their own lives ({counts}). Anyone who runs out is eliminated and the rest keep playing.", "Cada jugador tiene sus propias vidas ({counts}). Quien se queda sin vidas sale y los demás siguen."],
  "opt.noLivesTeam": ["Sem vidas: a equipe joga até todo mundo passar a vez ou alguém encerrar. Sem dicas.", "No lives: the team plays until everyone passes or someone ends the game. No hints.", "Sin vidas: el equipo juega hasta que todos pasen o alguien termine. Sin pistas."],
  "opt.noLivesDuel": ["Sem vidas: errou, passa a vez e segue o jogo.", "No lives: miss, pass the turn and keep playing.", "Sin vidas: si fallas, pasa el turno y sigue el juego."],
});

// ───────────── skins ─────────────
Object.assign(TEXTS, {
  "skin.change": ["Trocar skin", "Change skin", "Cambiar skin"],
  "skin.use": ["Usar esta skin", "Use this skin", "Usar esta skin"],
  "skin.of": ["Skin de {nome}", "{nome}'s skin", "Skin de {nome}"],
  "skin.custom": ["Personalizar", "Customize", "Personalizar"],
  "skin.inUse": ["em uso", "in use", "en uso"],
  "skin.special": ["Especial", "Special", "Especial"],
  "skin.prev": ["Anterior", "Previous", "Anterior"],
  "skin.next": ["Próximo", "Next", "Siguiente"],
  "skin.label": ["Skin: {nome}", "Skin: {nome}", "Skin: {nome}"],
  "group.Heróis": ["Heróis", "Heroes", "Héroes"],
  "group.Vilões": ["Vilões", "Villains", "Villanos"],
  "group.Animes": ["Animes", "Anime", "Animes"],
  "group.Desenhos": ["Desenhos", "Cartoons", "Dibujos"],
  "group.Filmes e séries": ["Filmes e séries", "Movies & TV", "Películas y series"],
  "group.Games": ["Games", "Games", "Videojuegos"],
  "group.Futebol": ["Futebol", "Soccer", "Fútbol"],
  "group.Profissões": ["Profissões", "Jobs", "Profesiones"],
  "builder.Rosto": ["Rosto", "Face", "Cara"],
  "builder.Cabelo": ["Cabelo", "Hair", "Pelo"],
  "builder.Cabeça": ["Cabeça", "Head", "Cabeza"],
  "builder.Roupa": ["Roupa", "Outfit", "Ropa"],
  "builder.Extras": ["Extras", "Extras", "Extras"],
  "ctrl.skin": ["Pele", "Skin tone", "Piel"],
  "ctrl.eyes": ["Olhos", "Eyes", "Ojos"],
  "ctrl.mouth": ["Boca", "Mouth", "Boca"],
  "ctrl.beard": ["Barba", "Beard", "Barba"],
  "ctrl.beardColor": ["Cor da barba", "Beard color", "Color de barba"],
  "ctrl.sameHair": ["Igual ao cabelo", "Same as hair", "Igual al pelo"],
  "ctrl.extra": ["Detalhe", "Detail", "Detalle"],
  "ctrl.hair": ["Corte", "Haircut", "Corte"],
  "ctrl.color": ["Cor", "Color", "Color"],
  "ctrl.head": ["Acessório", "Accessory", "Accesorio"],
  "ctrl.headColor": ["Cor principal", "Main color", "Color principal"],
  "ctrl.headColor2": ["Segunda cor", "Second color", "Segundo color"],
  "ctrl.capLetter": ["Letra do boné", "Cap letter", "Letra de la gorra"],
  "ctrl.shirt": ["Camisa", "Shirt", "Camiseta"],
  "ctrl.pattern": ["Estampa", "Print", "Estampado"],
  "ctrl.patternColor": ["Cor da estampa", "Print color", "Color del estampado"],
  "ctrl.number": ["Número", "Number", "Número"],
  "ctrl.sleeves": ["Mangas", "Sleeves", "Mangas"],
  "ctrl.sameShirt": ["Igual à camisa", "Same as shirt", "Igual a la camiseta"],
  "ctrl.belt": ["Cinto", "Belt", "Cinturón"],
  "ctrl.noBelt": ["Sem cinto", "No belt", "Sin cinturón"],
  "ctrl.legs": ["Calça", "Pants", "Pantalón"],
  "ctrl.cape": ["Capa", "Cape", "Capa"],
  "ctrl.noCape": ["Sem capa", "No cape", "Sin capa"],
  "ctrl.item": ["Na mão", "Holding", "En la mano"],
  "ctrl.bg": ["Fundo", "Background", "Fondo"],
  "ctrl.noBg": ["Sem fundo", "No background", "Sin fondo"],
});

// Nomes de skins prontas que mudam de idioma: [en, es] (os outros são iguais nos três).
const SKIN_NAMES = {
  aranha: ["Spider-Man", "Hombre Araña"], maravilha: ["Wonder Woman", "Mujer Maravilla"], ferro: ["Iron Man", "Iron Man"],
  capitao: ["Captain America", "Capitán América"], pantera: ["Black Panther", "Pantera Negra"], viuva: ["Black Widow", "Viuda Negra"],
  capita: ["Captain Marvel", "Capitana Marvel"], estranho: ["Doctor Strange", "Doctor Strange"], chapolin: ["El Chapulín Colorado", "El Chapulín Colorado"],
  coringa: ["Joker", "Guasón"], arlequina: ["Harley Quinn", "Harley Quinn"], malevola: ["Maleficent", "Maléfica"], duende: ["Green Goblin", "Duende Verde"],
  wandinha: ["Wednesday", "Merlina"], onze: ["Eleven", "Once"], jedi: ["Jedi Master", "Maestro Jedi"], joel: ["Survivor", "Superviviente"],
  peach: ["Princess Peach", "Princesa Peach"], geralt: ["Witcher", "Brujo"], ronaldo: ["Ronaldo Nazário", "Ronaldo Nazário"],
  astronauta: ["Astronaut", "Astronauta"], bombeiro: ["Firefighter", "Bombero"], medica: ["Doctor", "Médica"], robo: ["Robot", "Robot"],
  pirata: ["Pirate", "Pirata"], realeza: ["King/Queen", "Rey/Reina"], policial: ["Police officer", "Policía"], professora: ["Teacher", "Profesora"],
  cientista: ["Scientist", "Científica"], magico: ["Magician", "Mago"], palhaco: ["Clown", "Payaso"], detetive: ["Detective", "Detective"],
  fazendeiro: ["Farmer", "Granjero"], skatista: ["Skater", "Skater"], surfista: ["Surfer", "Surfista"],
  monica: ["Monica", "Mónica"], cebolinha: ["Jimmy Five", "Cebollita"], cascao: ["Smudge", "Cascarón"], magali: ["Maggy", "Magali"],
  picapau: ["Woody Woodpecker", "El Pájaro Loco"], chaves: ["El Chavo", "El Chavo del 8"],
};

function presetName(preset) {
  const tr = SKIN_NAMES[preset.id];
  return tr && lang !== "pt" ? tr[lang === "en" ? 0 : 1] : preset.name;
}

// Peças do editor: [en, es] por valor (o português é o rótulo original em avatars.js).
const PART_NAMES = {
  hair: { none: ["Bald", "Calvo"], buzz: ["Buzz cut", "Rapado"], short: ["Short", "Corto"], spiky: ["Spiky", "De punta"], messy: ["Messy", "Despeinado"], slick: ["Slicked", "Peinado"], side: ["Side fringe", "Flequillo de lado"], bob: ["Bob", "Melena corta"], long: ["Long", "Largo"], ponytail: ["Ponytail", "Coleta"], pigtails: ["Pigtails", "Dos coletas"], bun: ["Bun", "Moño"], curly: ["Curly", "Rizado"], afro: ["Afro", "Afro"], buns: ["Space buns", "Moñitos"], braids: ["Braids", "Trenzas"], dreads: ["Dreads", "Rastas"], mohawk: ["Mohawk", "Cresta"], fivehairs: ["Five hairs", "Cinco pelos"] },
  eyes: { normal: ["Normal", "Normal"], happy: ["Happy", "Feliz"], angry: ["Angry", "Enojado"], sleepy: ["Sleepy", "Dormido"], wide: ["Wide", "Abiertos"], lashes: ["Lashes", "Pestañas"], wink: ["Wink", "Guiño"], glasses: ["Glasses", "Lentes"], shades: ["Sunglasses", "Lentes de sol"] },
  mouth: { smile: ["Smile", "Sonrisa"], grin: ["Big grin", "Sonrisota"], smirk: ["Smirk", "Media sonrisa"], teeth: ["Buck teeth", "Dientón"], open: ["Surprised", "Sorprendido"], line: ["Serious", "Serio"], sad: ["Sad", "Triste"], tongue: ["Tongue out", "Lengua"], lips: ["Lipstick", "Labial"], evil: ["Evil", "Malvado"] },
  beard: { none: ["No beard", "Sin barba"], mustache: ["Mustache", "Bigote"], goatee: ["Goatee", "Perilla"], sideburns: ["Sideburns", "Patillas"], stubble: ["Stubble", "Barba de días"], beard: ["Beard", "Barba"], long: ["Long beard", "Barba larga"] },
  head: { none: ["Nothing", "Nada"], cap: ["Cap", "Gorra"], beanie: ["Beanie", "Gorro"], headband: ["Headband", "Cinta"], headphones: ["Headphones", "Auriculares"], bow: ["Bow", "Moño"], flowers: ["Flower crown", "Corona de flores"], crown: ["Crown", "Corona"], tiara: ["Tiara", "Tiara"], halo: ["Halo", "Aureola"], devil: ["Devil horns", "Cuernitos"], bighorns: ["Big horns", "Cuernos grandes"], antennae: ["Antennae", "Antenitas"], mouse: ["Mouse ears", "Orejas de ratón"], bunny: ["Bunny ears", "Orejas de conejo"], cat: ["Cat ears", "Orejas de gato"], fedora: ["Fedora", "Sombrero"], tophat: ["Top hat", "Galera"], straw: ["Straw hat", "Sombrero de paja"], cowboy: ["Cowboy hat", "Sombrero vaquero"], party: ["Party hat", "Gorro de fiesta"], bandana: ["Bandana", "Pañuelo"], pirate: ["Pirate hat", "Sombrero pirata"], wizard: ["Wizard hat", "Sombrero de mago"], chef: ["Chef hat", "Gorro de chef"], hardhat: ["Hard hat", "Casco de obra"], firehat: ["Firefighter helmet", "Casco de bombero"], viking: ["Viking helmet", "Casco vikingo"], knight: ["Knight helmet", "Yelmo"], astro: ["Space helmet", "Casco espacial"], robot: ["Robot head", "Cabeza de robot"], heromask: ["Hero mask", "Máscara de héroe"], ninja: ["Ninja mask", "Máscara ninja"], hood: ["Hood", "Capucha"] },
  pattern: { plain: ["Plain", "Lisa"], stripes: ["Stripes", "Rayas"], hoops: ["Hoops", "Franjas"], sash: ["Sash", "Banda diagonal"], dots: ["Polka dots", "Lunares"], plaid: ["Plaid", "Cuadros"], camo: ["Camo", "Camuflaje"], number: ["Number", "Número"], star: ["Star", "Estrella"], heart: ["Heart", "Corazón"], bolt: ["Lightning", "Rayo"], hoodie: ["Hoodie", "Sudadera"], tank: ["Tank top", "Musculosa"], suit: ["Suit", "Traje"], jacket: ["Jacket", "Chaqueta"], overalls: ["Overalls", "Overol"], armor: ["Armor", "Armadura"], robe: ["Robe", "Túnica"], scarf: ["Scarf", "Bufanda"] },
  extra: { none: ["Nothing", "Nada"], cheeks: ["Blush", "Mejillas"], freckles: ["Freckles", "Pecas"], mole: ["Mole", "Lunar"], scar: ["Scar", "Cicatriz"], bandaid: ["Band-aid", "Curita"], warpaint: ["War paint", "Pintura de guerra"], whiskers: ["Whiskers", "Bigotes"], nose: ["Clown nose", "Nariz de payaso"], domino: ["Eye mask", "Antifaz"], tattoo: ["Tattoo", "Tatuaje"], eyepatch: ["Eye patch", "Parche"] },
  item: { none: ["Nothing", "Nada"], ball: ["Ball", "Pelota"], mic: ["Microphone", "Micrófono"], phone: ["Phone", "Celular"], trophy: ["Trophy", "Trofeo"], sword: ["Sword", "Espada"], shield: ["Shield", "Escudo"], wand: ["Wand", "Varita"], balloon: ["Balloon", "Globo"], guitar: ["Guitar", "Guitarra"], pokeball: ["Poké Ball", "Poké Ball"], hammer: ["Hammer", "Martillo"], bat: ["Bat", "Bate"], book: ["Book", "Libro"], flask: ["Flask", "Frasco"], magnifier: ["Magnifier", "Lupa"], watch: ["Watch", "Reloj"] },
};

function partName(key, value, fallback) {
  const tr = PART_NAMES[key] && PART_NAMES[key][value];
  return tr && lang !== "pt" ? tr[lang === "en" ? 0 : 1] : fallback;
}

// ───────────── listas e editor ─────────────
Object.assign(TEXTS, {
  "lists.title": ["Escolha a lista", "Choose a list", "Elige la lista"],
  "lists.search": ["Pesquisar: copa, marvel, pokémon…", "Search: world cup, marvel, pokémon…", "Buscar: mundial, marvel, pokémon…"],
  "lists.searchAria": ["Pesquisar listas", "Search lists", "Buscar listas"],
  "lists.random": ["Sortear lista", "Random list", "Lista al azar"],
  "lists.suggest": ["Sugestões", "Suggestions", "Sugerencias"],
  "lists.cats": ["Categorias", "Categories", "Categorías"],
  "lists.back": ["← Categorias", "← Categories", "← Categorías"],
  "lists.all": ["Todas", "All", "Todas"],
  "lists.anySize": ["Qualquer tamanho", "Any size", "Cualquier tamaño"],
  "lists.record": ["Recorde: {n} pts ({nome})", "Record: {n} pts ({nome})", "Récord: {n} pts ({nome})"],
  "lists.teamRecord": ["Equipe: {n} pts", "Team: {n} pts", "Equipo: {n} pts"],
  "lists.none": ["Nenhuma lista encontrada. Tente outra palavra ou crie a sua.", "No lists found. Try another word or create your own.", "No se encontró ninguna lista. Prueba otra palabra o crea la tuya."],
  "lists.noneIn": ["Nenhuma lista encontrada no {mode}. Tente outra palavra ou crie a sua.", "No lists found in {mode}. Try another word or create your own.", "No se encontró ninguna lista en el {mode}. Prueba otra palabra o crea la tuya."],
  "lists.recent": ["jogada recentemente", "played recently", "jugada hace poco"],
  "lists.edit": ["Editar", "Edit", "Editar"],
  "lists.share": ["Compartilhar", "Share", "Compartir"],
  "lists.delete": ["Apagar", "Delete", "Borrar"],
  "lists.deleteConfirm": ["Apagar a lista \"{title}\"?", "Delete the list \"{title}\"?", "¿Borrar la lista \"{title}\"?"],
  "lists.badLink": ["Esse link de lista não é válido.", "This list link isn't valid.", "Este enlace de lista no es válido."],
  "lists.importConfirm": ["Adicionar a lista \"{title}\" ({n} itens) às suas listas?", "Add the list \"{title}\" ({n} items) to your lists?", "¿Agregar la lista \"{title}\" ({n} ítems) a tus listas?"],
  "lists.shared": ["Lista compartilhada", "Shared list", "Lista compartida"],
  "lists.langOnly": ["Listas em português", "Lists in English", "Listas en español"],
  "lists.langAll": ["Todos os idiomas", "All languages", "Todos los idiomas"],
  "editor.intro": ["Monte seu próprio tema. Coloque do mais óbvio (vale 1 ponto) ao menos óbvio (vale mais).", "Make your own topic. Go from the most obvious (worth 1 point) to the least obvious (worth the most).", "Arma tu propio tema. Ve de lo más obvio (vale 1 punto) a lo menos obvio (vale más)."],
  "editor.name": ["Nome da lista", "List name", "Nombre de la lista"],
  "editor.namePh": ["Ex.: Os 10 lanches favoritos da turma", "E.g.: The group's 10 favorite snacks", "Ej.: Los 10 snacks favoritos del grupo"],
  "editor.size": ["Tamanho", "Size", "Tamaño"],
  "editor.save": ["Salvar lista", "Save list", "Guardar lista"],
  "editor.edit": ["Editar lista", "Edit list", "Editar lista"],
  "editor.first": ["O mais óbvio (vale 1 ponto)", "The most obvious (worth 1 point)", "Lo más obvio (vale 1 punto)"],
  "editor.last": ["O menos óbvio (vale {n} pontos)", "The least obvious (worth {n} points)", "Lo menos obvio (vale {n} puntos)"],
  "editor.item": ["Item nº {n}", "Item No. {n}", "Ítem n.º {n}"],
  "editor.alts": ["Outras respostas aceitas, separadas por vírgula (opcional)", "Other accepted answers, separated by commas (optional)", "Otras respuestas aceptadas, separadas por comas (opcional)"],
  "editor.errName": ["Dê um nome para a lista.", "Give the list a name.", "Ponle un nombre a la lista."],
  "editor.errEmpty": ["Preencha o item nº {n}.", "Fill in item No. {n}.", "Completa el ítem n.º {n}."],
  "editor.errDup": ["Os itens nº {a} e nº {b} são iguais.", "Items No. {a} and No. {b} are the same.", "Los ítems n.º {a} y n.º {b} son iguales."],
  "editor.byYou": ["Lista criada por você", "List created by you", "Lista creada por ti"],
});

// ───────────── categorias ─────────────
Object.assign(TEXTS, {
  "cat.minhas": ["Minhas listas", "My lists", "Mis listas"],
  "cat.geografia": ["Geografia", "Geography", "Geografía"],
  "cat.brasil": ["Brasil", "Brazil", "Brasil"],
  "cat.futebol": ["Futebol", "Soccer", "Fútbol"],
  "cat.esporte": ["Esporte", "Sports", "Deportes"],
  "cat.filmes": ["Filmes", "Movies", "Películas"],
  "cat.herois": ["Heróis", "Heroes", "Héroes"],
  "cat.animes": ["Animes", "Anime", "Animes"],
  "cat.games": ["Games", "Video games", "Videojuegos"],
  "cat.musica": ["Música", "Music", "Música"],
  "cat.tv": ["TV", "TV", "TV"],
  "cat.ciencia": ["Ciência", "Science", "Ciencia"],
  "cat.matematica": ["Matemática", "Math", "Matemáticas"],
  "cat.historia": ["História", "History", "Historia"],
  "cat.curiosidades": ["Curiosidades", "Trivia", "Curiosidades"],
  "cat.idiomas": ["Idiomas", "Languages", "Idiomas"],
  "cat.animais": ["Animais", "Animals", "Animales"],
  "cat.frases": ["Frases do dia a dia", "Everyday sayings", "Frases del día a día"],
  "cat.personagens": ["Personagens", "Characters", "Personajes"],
  "cat.comida": ["Comida e bebida", "Food & drink", "Comida y bebida"],
  "cat.diaadia": ["Dia a dia", "Everyday life", "Día a día"],
  "cat.casais": ["Casais", "Couples", "Parejas"],
  "cat.biblia": ["Bíblia", "Bible", "Biblia"],
});

// ───────────── partida ─────────────
Object.assign(TEXTS, {
  "game.items": ["{n} item¦{n} itens", "{n} item¦{n} items", "{n} ítem¦{n} ítems"],
  "game.source": ["Fonte: {src}", "Source: {src}", "Fuente: {src}"],
  "game.listLeft": ["{n} pts ainda na lista", "{n} pts still on the list", "{n} pts todavía en la lista"],
  "game.team": ["Equipe", "Team", "Equipo"],
  "game.you": ["Você", "You", "Tú"],
  "game.list": ["Lista", "List", "Lista"],
  "game.toWin": ["Faltam {n} pts para vencer a lista", "{n} pts to go to beat the list", "Faltan {n} pts para ganarle a la lista"],
  "game.listBeaten": ["A lista já foi vencida!", "The list is beaten!", "¡Ya le ganaron a la lista!"],
  "game.livesOf": ["{a} de {b} vidas", "{a} of {b} lives", "{a} de {b} vidas"],
  "game.lives": ["{n} vida¦{n} vidas", "{n} life¦{n} lives", "{n} vida¦{n} vidas"],
  "game.out": ["fora: sem vidas", "out: no lives", "fuera: sin vidas"],
  "game.hits": ["{n} acerto¦{n} acertos", "{n} hit¦{n} hits", "{n} acierto¦{n} aciertos"],
  "game.turnOf": ["Vez de", "Turn", "Turno de"],
  "game.found": ["Encontrados: {a} de {b}", "Found: {a} of {b}", "Encontrados: {a} de {b}"],
  "game.wrong": ["Chutes errados:", "Wrong guesses:", "Respuestas fallidas:"],
  "game.guessPh": ["Seu palpite", "Your guess", "Tu respuesta"],
  "game.guessAria": ["Palpite", "Guess", "Respuesta"],
  "game.guessBtn": ["Chutar", "Guess", "Responder"],
  "game.waitTurn": ["Vez de {nome}…", "{nome}'s turn…", "Turno de {nome}…"],
  "game.hintBtn": ["Dica (−1 vida)", "Hint (−1 life)", "Pista (−1 vida)"],
  "game.hintCancel": ["Cancelar dica", "Cancel hint", "Cancelar pista"],
  "game.pass": ["Passar a vez", "Pass", "Pasar turno"],
  "ideas.title": ["Ideias para chutar", "Guess ideas", "Ideas para adivinar"],
  "ideas.of": ["Ideias de {name}", "{name}'s ideas", "Ideas de {name}"],
  "ideas.ph": ["Anote uma ideia para não esquecer", "Jot down an idea so you don't forget", "Anota una idea para no olvidarla"],
  "ideas.add": ["Anotar", "Add", "Anotar"],
  "ideas.empty": ["Teve uma ideia fora da sua vez? Anote aqui e toque nela quando chegar a sua vez.", "Had an idea when it wasn't your turn? Jot it here and tap it when your turn comes.", "¿Se te ocurrió algo fuera de tu turno? Anótalo aquí y tócalo cuando llegue tu turno."],
  "ideas.remove": ["Apagar ideia", "Delete idea", "Borrar idea"],
  "game.end": ["Encerrar partida", "End game", "Terminar partida"],
  "hint.letters": ["{n} letra¦{n} letras", "{n} letter¦{n} letters", "{n} letra¦{n} letras"],
  "hint.words": ["{n} palavra¦{n} palavras", "{n} word¦{n} words", "{n} palabra¦{n} palabras"],
  "fx.streak": ["{n} seguidos", "{n} in a row", "{n} seguidos"],
  "fx.time": ["tempo!", "time!", "¡tiempo!"],
  "fx.miss": ["errou", "miss", "fallo"],
  "fx.life": ["-1 vida", "-1 life", "-1 vida"],
  "hype.low": [
    ["Esse era fácil, hein.", "O óbvio também conta.", "Pontinho garantido.", "Começou pelo básico."],
    ["That one was easy.", "The obvious counts too.", "A point in the bag.", "Starting with the basics."],
    ["Esa era fácil, eh.", "Lo obvio también cuenta.", "Puntito asegurado.", "Empezó por lo básico."],
  ],
  "hype.mid": [
    ["Boa!", "Mandou bem!", "Lâmpada acesa!", "Isso aí!", "Tá esperto!"],
    ["Nice!", "Well played!", "Light bulb on!", "That's it!", "Sharp!"],
    ["¡Bien!", "¡Muy bien!", "¡Se prendió la lamparita!", "¡Eso es!", "¡Qué listo!"],
  ],
  "hype.high": [
    ["Que isso?!", "Ninguém esperava essa!", "Gênio detectado!", "Tirou da cartola!", "Esse ninguém lembrava!"],
    ["Whoa?!", "Nobody saw that coming!", "Genius detected!", "Pulled it out of a hat!", "Nobody remembered that one!"],
    ["¿¡Qué es eso!?", "¡Nadie esperaba esa!", "¡Genio detectado!", "¡La sacó de la galera!", "¡Esa nadie la recordaba!"],
  ],
  "streak": [
    ["{nome} está em chamas: {n} seguidos!", "Alguém para {nome}! {n} acertos seguidos!", "{nome} ligou o modo turbo: {n} seguidos!", "{n} seguidos! {nome} tá com a cola, só pode."],
    ["{nome} is on fire: {n} in a row!", "Somebody stop {nome}! {n} hits in a row!", "{nome} hit turbo mode: {n} in a row!", "{n} in a row! {nome} must have the answers."],
    ["{nome} está en llamas: ¡{n} seguidos!", "¡Que alguien pare a {nome}! ¡{n} aciertos seguidos!", "{nome} activó el modo turbo: ¡{n} seguidos!", "¡{n} seguidos! {nome} tiene la chuleta, seguro."],
  ],
  "fb.hit": ["{item} é o nº {n}: +{n} para {nome}.", "{item} is No. {n}: +{n} for {nome}.", "{item} es el n.º {n}: +{n} para {nome}."],
  "fb.hitTeam": ["{item} é o nº {n}: +{n} para {nome} ({team}).", "{item} is No. {n}: +{n} for {nome} ({team}).", "{item} es el n.º {n}: +{n} para {nome} ({team})."],
  "fb.dup": ["{item} já foi encontrado por {nome}. Tente outro!", "{item} was already found by {nome}. Try another!", "{nome} ya encontró {item}. ¡Prueba otro!"],
  "fb.tried": ["\"{text}\" já foi tentado. Tente outro!", "\"{text}\" was already tried. Try another!", "\"{text}\" ya se intentó. ¡Prueba otro!"],
  "fb.notIn": ["\"{text}\" não está na lista.", "\"{text}\" isn't on the list.", "\"{text}\" no está en la lista."],
  "fb.timeUp": ["Acabou o tempo de {nome}!", "{nome} ran out of time!", "¡Se acabó el tiempo de {nome}!"],
  "fb.pass": ["Passa a vez.", "Next player.", "Pasa el turno."],
  "fb.noLives": ["Acabaram as vidas!", "Out of lives!", "¡Se acabaron las vidas!"],
  "fb.noLivesTeam": ["Acabaram as vidas da equipe!", "The team is out of lives!", "¡Se acabaron las vidas del equipo!"],
  "fb.livesLeft": ["Resta 1 vida!¦Restam {n} vidas.", "1 life left!¦{n} lives left.", "¡Queda 1 vida!¦Quedan {n} vidas."],
  "fb.allOut": ["Todo mundo ficou sem vidas!", "Everyone is out of lives!", "¡Todos se quedaron sin vidas!"],
  "fb.playerOut": ["{nome} ficou sem vidas e está fora!", "{nome} is out of lives and out of the game!", "¡{nome} se quedó sin vidas y está fuera!"],
  "fb.playerLives": ["{nome}: resta 1 vida.¦{nome}: restam {n} vidas.", "{nome}: 1 life left.¦{nome}: {n} lives left.", "{nome}: queda 1 vida.¦{nome}: quedan {n} vidas."],
  "fb.allFound": ["Todos os {n} foram encontrados!", "All {n} were found!", "¡Encontraron los {n}!"],
  "fb.allPassTeam": ["A equipe toda passou a vez. A lista fica com o resto!", "The whole team passed. The list keeps the rest!", "Todo el equipo pasó. ¡La lista se queda con el resto!"],
  "fb.allPass": ["Todo mundo passou a vez. Ninguém lembra de mais nenhum!", "Everyone passed. Nobody can think of any more!", "Todos pasaron. ¡Nadie recuerda ninguno más!"],
  "fb.passed": ["{nome} passou a vez.", "{nome} passed.", "{nome} pasó el turno."],
  "fb.hintPick": ["Toque num item escondido para ver a primeira letra. Custa 1 vida.", "Tap a hidden item to see its first letter. Costs 1 life.", "Toca un ítem oculto para ver la primera letra. Cuesta 1 vida."],
  "fb.hint": ["Dica do nº {n}: {hint}.", "Hint for No. {n}: {hint}.", "Pista del n.º {n}: {hint}."],
  "fb.ended": ["Partida encerrada.", "Game ended.", "Partida terminada."],
  "confirm.leaveOnline": ["Sair da partida online? Você sai da sala.", "Leave the online game? You'll leave the room.", "¿Salir de la partida online? Saldrás de la sala."],
  "confirm.leaveGame": ["Sair da partida atual?", "Leave the current game?", "¿Salir de la partida actual?"],
  "confirm.end": ["Encerrar a partida e ver o resultado?", "End the game and see the results?", "¿Terminar la partida y ver el resultado?"],
  "confirm.closeRoom": ["Fechar a sala para todo mundo?", "Close the room for everyone?", "¿Cerrar la sala para todos?"],
  "confirm.leaveRoom": ["Sair da sala?", "Leave the room?", "¿Salir de la sala?"],
});

// ───────────── resultado ─────────────
Object.assign(TEXTS, {
  "and": ["e", "and", "y"],
  "results.fullList": ["A lista completa", "The full list", "La lista completa"],
  "results.share": ["Compartilhar resultado", "Share result", "Compartir resultado"],
  "results.changePlayers": ["Trocar jogadores", "Change players", "Cambiar jugadores"],
  "results.changeMode": ["Trocar modo", "Change mode", "Cambiar modo"],
  "rs.rematch": ["Revanche (outra lista)", "Rematch (another list)", "Revancha (otra lista)"],
  "rs.otherList": ["Jogar outra lista", "Play another list", "Jugar otra lista"],
  "rs.record": ["Novo recorde da lista: {n} pts!", "New list record: {n} pts!", "¡Nuevo récord de la lista: {n} pts!"],
  "rs.won": ["{nome} venceu!", "{nome} wins!", "¡{nome} ganó!"],
  "rs.tieTop": ["Empate no topo!", "Tie at the top!", "¡Empate en la cima!"],
  "rs.tieTeams": ["Empate entre os times!", "The teams are tied!", "¡Empate entre los equipos!"],
  "rs.perfect.solo": ["Você gabaritou a lista!", "You aced the list!", "¡Completaste la lista!"],
  "rs.perfect.team": ["Gabaritaram a lista!", "You aced the list!", "¡Completaron la lista!"],
  "rs.win.solo": ["Você venceu a lista!", "You beat the list!", "¡Le ganaste a la lista!"],
  "rs.win.team": ["A equipe venceu a lista!", "The team beat the list!", "¡El equipo le ganó a la lista!"],
  "rs.lose.all": ["A lista venceu.", "The list won.", "Ganó la lista."],
  "rs.tie.all": ["Empate com a lista!", "Tied with the list!", "¡Empate con la lista!"],
  "rs.itemsOf": ["{a} de {b} itens", "{a} of {b} items", "{a} de {b} ítems"],
  "rs.livesLost": ["{n} vida perdida¦{n} vidas perdidas", "{n} life lost¦{n} lives lost", "{n} vida perdida¦{n} vidas perdidas"],
  "rs.hints": ["{n} dica¦{n} dicas", "{n} hint¦{n} hints", "{n} pista¦{n} pistas"],
  "rs.leftInList": ["{n} pts ficaram na lista", "{n} pts stayed on the list", "{n} pts quedaron en la lista"],
  "rs.misses": ["{n} erro¦{n} erros", "{n} miss¦{n} misses", "{n} fallo¦{n} fallos"],
  "rs.timeouts": ["{n} no tempo", "{n} timed out", "{n} sin tiempo"],
  "rs.passes": ["passou {n}", "passed {n}", "pasó {n}"],
  "rs.noHits": ["nenhum acerto", "no hits", "ningún acierto"],
  "rs.toList": ["+{n} lista", "+{n} list", "+{n} lista"],
  "rs.nobody": ["ninguém", "nobody", "nadie"],
  "rv.finalScore": ["Sua pontuação final…", "Your final score…", "Tu puntaje final…"],
  "rv.points": ["{n} pontos", "{n} points", "{n} puntos"],
  "rv.winnerIs": ["E o vencedor é…", "And the winner is…", "Y el ganador es…"],
  "rv.teamIs": ["E o time vencedor é…", "And the winning team is…", "Y el equipo ganador es…"],
  "rv.resultIs": ["E o resultado é…", "And the result is…", "Y el resultado es…"],
  "rv.tie": ["EMPATE!", "TIE!", "¡EMPATE!"],
  "rv.tieEach": ["{nomes} com {n} pontos cada", "{nomes} with {n} points each", "{nomes} con {n} puntos cada uno"],
  "rv.wonWith": ["venceu com {n} pontos", "won with {n} points", "ganó con {n} puntos"],
  "rv.wonBy": ["venceu por {a} a {b}", "won {a} to {b}", "ganó {a} a {b}"],
  "rv.score": ["{a} a {b}", "{a} to {b}", "{a} a {b}"],
  "rv.perfect": ["GABARITOU!", "PERFECT!", "¡PERFECTO!"],
  "rv.perfectSub.solo": ["Você achou todos os {n} itens", "You found all {n} items", "Encontraste los {n} ítems"],
  "rv.perfectSub.team": ["A equipe achou todos os {n} itens", "The team found all {n} items", "El equipo encontró los {n} ítems"],
  "rv.victory": ["VITÓRIA!", "VICTORY!", "¡VICTORIA!"],
  "rv.winSub.solo": ["Você venceu a lista por {a} a {b}", "You beat the list {a} to {b}", "Le ganaste a la lista {a} a {b}"],
  "rv.winSub.team": ["A equipe venceu a lista por {a} a {b}", "The team beat the list {a} to {b}", "El equipo le ganó a la lista {a} a {b}"],
  "rv.listWon": ["A LISTA VENCEU", "THE LIST WON", "GANÓ LA LISTA"],
  "rv.loseSub": ["{b} a {a}. Revanche?", "{b} to {a}. Rematch?", "{b} a {a}. ¿Revancha?"],
  "rv.tieList": ["{a} a {b} com a lista", "{a} to {b} with the list", "{a} a {b} con la lista"],
  "hl.best": ["Jogada da partida", "Play of the game", "Jugada de la partida"],
  "hl.bestText": ["{nome} achou {item}, o nº {n}.", "{nome} found {item}, No. {n}.", "{nome} encontró {item}, el n.º {n}."],
  "hl.zero": ["Placar zerado", "Zero on the board", "Marcador en cero"],
  "hl.zeroText": ["Ninguém achou nada. A lista agradece a visita.", "Nobody found anything. The list thanks you for stopping by.", "Nadie encontró nada. La lista agradece la visita."],
  "hl.perfect": ["Lista gabaritada", "List aced", "Lista completa"],
  "hl.perfectText": ["Todos os {n} itens. Não sobrou nada pra lista!", "All {n} items. Nothing left for the list!", "Los {n} ítems. ¡No le quedó nada a la lista!"],
  "hl.hardest": ["O mais difícil", "The hardest one", "El más difícil"],
  "hl.hardestText": ["O nº {n} era {item}. Alguém lembrava?", "No. {n} was {item}. Did anyone remember?", "El n.º {n} era {item}. ¿Alguien lo recordaba?"],
  "hl.obvious": ["Esqueceram o óbvio", "Forgot the obvious", "Se olvidaron de lo obvio"],
  "hl.obviousText": ["Ninguém disse {item}, o nº 1!", "Nobody said {item}, No. 1!", "¡Nadie dijo {item}, el n.º 1!"],
  "hl.streak": ["Sequência", "Streak", "Racha"],
  "hl.streakText": ["{nome} acertou {n} seguidos.", "{nome} got {n} in a row.", "{nome} acertó {n} seguidos."],
  "aw.won": ["Venceu", "Winner", "Ganó"],
  "aw.last": ["Achou o nº {n}", "Found No. {n}", "Encontró el n.º {n}"],
  "aw.clutch": ["Acertou com 1 vida", "Clutch with 1 life", "Acertó con 1 vida"],
  "aw.noMiss": ["Zero erros", "No misses", "Cero fallos"],
  "aw.guesser": ["Chutador oficial", "Official guesser", "Adivinador oficial"],
  "aw.slept": ["Dormiu no relógio¦Dormiu {n}x no relógio", "Fell asleep on the clock¦Fell asleep {n}x on the clock", "Se durmió con el reloj¦Se durmió {n} veces con el reloj"],
  "aw.passed": ["Passou {n} vezes", "Passed {n} times", "Pasó {n} veces"],
  "aw.obvious": ["Só o óbvio", "Only the obvious", "Solo lo obvio"],
  "aw.share": ["{n}% dos pontos", "{n}% of the points", "{n}% de los puntos"],
  "contest.title": ["Algum chute estava certo?", "Was any guess actually right?", "¿Alguna respuesta era correcta?"],
  "contest.help": ["Se a turma concordar que um chute valia (faltou um apelido na lista), escolha o item. Os pontos entram no placar e essa resposta passa a valer nas próximas partidas.", "If everyone agrees a guess should count (the list was missing a nickname), pick the item. The points go on the scoreboard and that answer will count in future games.", "Si el grupo está de acuerdo en que una respuesta valía (le faltaba un apodo a la lista), elige el ítem. Los puntos se suman y esa respuesta valdrá en las próximas partidas."],
  "contest.by": ["chute de {nome}", "guess by {nome}", "respuesta de {nome}"],
  "contest.which": ["Qual item era “{text}”?", "Which item was “{text}”?", "¿Qué ítem era “{text}”?"],
  "contest.pick": ["Era qual item?", "Which item was it?", "¿Qué ítem era?"],
  "contest.option": ["nº {n} · {item}", "No. {n} · {item}", "n.º {n} · {item}"],
  "contest.accept": ["Aceitar", "Accept", "Aceptar"],
  "contest.accepted": ["Aceito! “{text}” valeu o nº {n}: +{n} para {nome}.", "Accepted! “{text}” counts as No. {n}: +{n} for {nome}.", "¡Aceptado! “{text}” vale el n.º {n}: +{n} para {nome}."],
});

// Frases do resultado (sorteadas). {nome} é o jogador.
Object.assign(TEXTS, {
  "ph.1": [
    ["{nome} jogou como quem tem a cola no bolso.", "Alguém confere se {nome} não estava no Google.", "{nome} sabe até a senha do Wi-Fi do vizinho.", "Pode chamar {nome} de enciclopédia ambulante.", "{nome} não falou o óbvio. Falou o certo.", "O cérebro de {nome} roda a 165 Hz.", "{nome} veio, viu e gabaritou (quase)."],
    ["{nome} played like they had the answer key.", "Someone check {nome} wasn't on Google.", "{nome} even knows the neighbor's Wi-Fi password.", "Call {nome} a walking encyclopedia.", "{nome} didn't say the obvious. They said the right thing.", "{nome}'s brain runs at 165 Hz.", "{nome} came, saw and (almost) aced it."],
    ["{nome} jugó como si tuviera las respuestas en el bolsillo.", "Que alguien revise que {nome} no estaba en Google.", "{nome} sabe hasta la clave del Wi-Fi del vecino.", "Pueden llamar a {nome} enciclopedia ambulante.", "{nome} no dijo lo obvio. Dijo lo correcto.", "El cerebro de {nome} va a 165 Hz.", "{nome} vino, vio y (casi) lo completó todo."],
  ],
  "ph.2": [
    ["{nome} bateu na trave. Na trave!", "Prata também brilha, {nome}.", "Faltou um fio de luz pra {nome} ganhar.", "{nome} vai pedir revanche, pode anotar.", "Vice com cara de campeão, {nome}."],
    ["{nome} hit the post. The post!", "Silver shines too, {nome}.", "{nome} was a hair away from winning.", "{nome} will ask for a rematch, mark my words.", "Runner-up with a champion's face, {nome}."],
    ["{nome} pegó en el palo. ¡En el palo!", "La plata también brilla, {nome}.", "A {nome} le faltó un pelito para ganar.", "{nome} va a pedir revancha, anótalo.", "Subcampeón con cara de campeón, {nome}."],
  ],
  "ph.3": [
    ["Bronze com gostinho de ouro pra {nome}.", "{nome} subiu no pódio no sufoco.", "Terceiro lugar e muita dignidade, {nome}.", "{nome} garantiu a foto no pódio."],
    ["Bronze that tastes like gold for {nome}.", "{nome} squeezed onto the podium.", "Third place and lots of dignity, {nome}.", "{nome} made it into the podium photo."],
    ["Bronce con sabor a oro para {nome}.", "{nome} llegó al podio sufriendo.", "Tercer lugar y mucha dignidad, {nome}.", "{nome} se aseguró la foto en el podio."],
  ],
  "ph.rest": [
    ["{nome} estava aquecendo pra próxima.", "A lâmpada de {nome} piscou, mas acendeu.", "{nome} participou. E isso é lindo.", "Na próxima é de {nome}. Talvez."],
    ["{nome} was warming up for the next one.", "{nome}'s light bulb flickered, but it lit up.", "{nome} took part. And that's beautiful.", "Next time it's {nome}'s. Maybe."],
    ["{nome} estaba calentando para la próxima.", "La lamparita de {nome} parpadeó, pero se encendió.", "{nome} participó. Y eso es hermoso.", "La próxima es de {nome}. Tal vez."],
  ],
  "ph.last": [
    ["{nome} veio pelo lanche e saiu com o lanche.", "Pelo menos a skin de {nome} tava bonita.", "{nome}, o importante é competir… né?", "A lanterna é de {nome}. Alguém tem que iluminar."],
    ["{nome} came for the snacks and left with the snacks.", "At least {nome}'s skin looked good.", "{nome}, it's the taking part that counts… right?", "{nome} brings up the rear. Someone has to."],
    ["{nome} vino por los snacks y se fue con los snacks.", "Al menos la skin de {nome} estaba linda.", "{nome}, lo importante es competir… ¿no?", "El farolito rojo es de {nome}. Alguien tiene que iluminar."],
  ],
  "ph.zero": [
    ["{nome} jogou no modo avião.", "Zero pontos e muita confiança, {nome}.", "{nome} chutou mais que goleiro em pênalti.", "{nome} está guardando as respostas pra próxima."],
    ["{nome} played in airplane mode.", "Zero points and lots of confidence, {nome}.", "{nome} guessed more than a goalie on a penalty.", "{nome} is saving the answers for next time."],
    ["{nome} jugó en modo avión.", "Cero puntos y mucha confianza, {nome}.", "{nome} adivinó más que un arquero en un penal.", "{nome} se está guardando las respuestas para la próxima."],
  ],
  "ph.tie": [
    ["Empate no topo. Desempate no par ou ímpar!", "{nome} dividiu a coroa. Ninguém dorme hoje."],
    ["Tie at the top. Settle it with rock-paper-scissors!", "{nome} shares the crown. Nobody sleeps tonight."],
    ["Empate en la cima. ¡Se define con piedra, papel o tijera!", "{nome} comparte la corona. Hoy nadie duerme."],
  ],
  "ph.solo.perfect": [["Gabaritou! {nome} é a própria usina elétrica."], ["Perfect! {nome} is a power plant."], ["¡Perfecto! {nome} es una central eléctrica."]],
  "ph.solo.great": [
    ["Holofote! {nome} quase zerou a lista.", "{nome} acendeu o estádio inteiro."],
    ["Spotlight! {nome} nearly cleared the list.", "{nome} lit up the whole stadium."],
    ["¡Reflector! {nome} casi completa la lista.", "{nome} iluminó el estadio entero."],
  ],
  "ph.solo.good": [
    ["Lâmpada acesa! Mandou bem, {nome}.", "{nome} fez bonito. Dá pra postar."],
    ["Light bulb on! Well played, {nome}.", "{nome} did great. Worth posting."],
    ["¡Lamparita encendida! Muy bien, {nome}.", "{nome} lo hizo genial. Para publicarlo."],
  ],
  "ph.solo.ok": [
    ["Meia-luz. Dá pra ler um livro, {nome}.", "{nome} tá no caminho. Bora de novo?"],
    ["Half light. Enough to read a book, {nome}.", "{nome} is on the way. Another round?"],
    ["Media luz. Alcanza para leer un libro, {nome}.", "{nome} va por buen camino. ¿Otra vez?"],
  ],
  "ph.solo.low": [
    ["Tá piscando… falta energia, {nome}.", "{nome} achou o básico. A lista riu baixinho."],
    ["Flickering… low power, {nome}.", "{nome} found the basics. The list chuckled."],
    ["Parpadea… falta energía, {nome}.", "{nome} encontró lo básico. La lista se rió bajito."],
  ],
  "ph.solo.zero": [
    ["Lâmpada queimada. Bora de novo, {nome}?", "{nome} jogou no modo avião."],
    ["Burnt-out bulb. Try again, {nome}?", "{nome} played in airplane mode."],
    ["Lamparita quemada. ¿Otra vez, {nome}?", "{nome} jugó en modo avión."],
  ],
  "tph.win": [
    ["Time entrosado é outra coisa.", "A lista não teve a menor chance.", "Cérebros conectados no mesmo Wi-Fi.", "Trabalho em equipe: funciona!", "A lista pediu pra sair."],
    ["A team in sync is something else.", "The list never stood a chance.", "Brains on the same Wi-Fi.", "Teamwork: it works!", "The list asked to be subbed off."],
    ["Un equipo afinado es otra cosa.", "La lista no tuvo ninguna chance.", "Cerebros conectados al mismo Wi-Fi.", "Trabajo en equipo: ¡funciona!", "La lista pidió el cambio."],
  ],
  "tph.perfect": [
    ["Gabaritaram! A lista pediu música no Fantástico.", "Nenhum item escapou. Que equipe!"],
    ["Perfect! The list is asking for a replay.", "Not a single item escaped. What a team!"],
    ["¡Perfecto! La lista pide la repetición.", "No se escapó ningún ítem. ¡Qué equipo!"],
  ],
  "tph.lose": [
    ["A lista mandou nessa. Revanche?", "Faltou energia na tomada da equipe.", "Hoje a lista saiu de cabeça erguida.", "A lista ganhou e já está se achando."],
    ["The list ruled this one. Rematch?", "The team's batteries ran low.", "Today the list walks away with its head high.", "The list won and it's already showing off."],
    ["La lista mandó en esta. ¿Revancha?", "Al equipo le faltó energía.", "Hoy la lista se fue con la frente en alto.", "La lista ganó y ya se la cree."],
  ],
  "tph.tie": [["Empate com a lista. Ninguém dorme hoje."], ["Tied with the list. Nobody sleeps tonight."], ["Empate con la lista. Hoy nadie duerme."]],
  "tph.mvp": [
    ["{nome} carregou a equipe nas costas.", "Craque da rodada: {nome}.", "{nome} é o cérebro da equipe.", "Se fosse futebol, {nome} vestia a 10."],
    ["{nome} carried the team.", "Player of the round: {nome}.", "{nome} is the team's brain.", "If this were soccer, {nome} would wear the 10."],
    ["{nome} cargó al equipo en la espalda.", "Figura de la ronda: {nome}.", "{nome} es el cerebro del equipo.", "Si fuera fútbol, {nome} usaría la 10."],
  ],
  "tph.help": [
    ["{nome} fez a parte e ajudou a equipe.", "Cada ponto conta. Valeu, {nome}!", "{nome}: peça importante do time.", "Ponto dado, ponto ganho, {nome}."],
    ["{nome} did their part and helped the team.", "Every point counts. Thanks, {nome}!", "{nome}: a key piece of the team.", "Every point matters, {nome}."],
    ["{nome} hizo su parte y ayudó al equipo.", "Cada punto cuenta. ¡Gracias, {nome}!", "{nome}: pieza clave del equipo.", "Punto a punto, {nome}."],
  ],
  "tph.lost": [
    ["{nome} lutou até o fim.", "O time não ajudou {nome}, né?", "Na revanche {nome} vira o jogo."],
    ["{nome} fought to the end.", "The team didn't help {nome}, did it?", "In the rematch {nome} turns it around."],
    ["{nome} luchó hasta el final.", "El equipo no ayudó a {nome}, ¿no?", "En la revancha {nome} da vuelta el partido."],
  ],
  "tph.zero": [
    ["{nome} foi da torcida organizada.", "{nome} veio pelo lanche, né?", "{nome} estava aquecendo pra próxima."],
    ["{nome} was in the cheering section.", "{nome} came for the snacks, right?", "{nome} was warming up for the next one."],
    ["{nome} estuvo en la hinchada.", "{nome} vino por los snacks, ¿no?", "{nome} estaba calentando para la próxima."],
  ],
});

// ───────────── lista do dia, perfil, conta e online ─────────────
Object.assign(TEXTS, {
  "daily.title": ["Lista do dia", "Daily list", "Lista del día"],
  "daily.tag": ["Lista do dia #{n}", "Daily list #{n}", "Lista del día #{n}"],
  "daily.pitch": ["Você contra a lista: 10 itens, 3 vidas.", "You against the list: 10 items, 3 lives.", "Tú contra la lista: 10 ítems, 3 vidas."],
  "daily.done": ["Você fez {a} de {b} pts. Volte amanhã para a #{next}.", "You scored {a} of {b} pts. Come back tomorrow for #{next}.", "Hiciste {a} de {b} pts. Vuelve mañana para la #{next}."],
  "daily.doneWon": ["Você fez {a} de {b} pts e venceu a lista. Volte amanhã para a #{next}.", "You scored {a} of {b} pts and beat the list. Come back tomorrow for #{next}.", "Hiciste {a} de {b} pts y le ganaste a la lista. Vuelve mañana para la #{next}."],
  "daily.same": ["Todo mundo joga a mesma lista hoje. Compare o resultado com os amigos.", "Everyone plays the same list today. Compare results with your friends.", "Hoy todos juegan la misma lista. Compara el resultado con tus amigos."],
  "daily.streak": ["Sequência: {n} dia.¦Sequência: {n} dias.", "Streak: {n} day.¦Streak: {n} days.", "Racha: {n} día.¦Racha: {n} días."],
  "daily.again": ["Jogar de novo (não conta)", "Play again (doesn't count)", "Jugar de nuevo (no cuenta)"],
  "daily.play": ["Jogar a lista do dia", "Play the daily list", "Jugar la lista del día"],
  "rank.short": ["{pos}º de {total}", "#{pos} of {total}", "{pos}.º de {total}"],
  "rank.anon": ["Jogador", "Player", "Jugador"],
  "daily.livesShare": ["vidas {a}/{b}", "lives {a}/{b}", "vidas {a}/{b}"],
  "daily.ptsOf": ["{a} de {b} pts", "{a} of {b} pts", "{a} de {b} pts"],
  "daily.iWon": ["Venci a lista!", "I beat the list!", "¡Le gané a la lista!"],
  "st.games": ["partidas", "games", "partidas"],
  "st.points": ["pontos somados", "total points", "puntos sumados"],
  "st.hits": ["acertos", "hits", "aciertos"],
  "st.rate": ["dos chutes certos", "of guesses right", "de respuestas correctas"],
  "st.vsWins": ["vitórias contra a lista", "wins against the list", "victorias contra la lista"],
  "st.perfect": ["lista gabaritada¦listas gabaritadas", "list aced¦lists aced", "lista completa¦listas completas"],
  "st.dailyStreak": ["dias seguidos na lista do dia", "days in a row on the daily list", "días seguidos en la lista del día"],
  "st.bestStreak": ["maior sequência", "best streak", "mejor racha"],
  "st.best": ["Maior acerto: {n}, {item} ({list}), por {nome}.", "Best hit: {n}, {item} ({list}), by {nome}.", "Mejor acierto: {n}, {item} ({list}), de {nome}."],
  "st.no": ["nº {n}", "No. {n}", "n.º {n}"],
  "st.empty": ["Jogue uma partida para começar suas estatísticas.", "Play a game to start your stats.", "Juega una partida para empezar tus estadísticas."],
  "st.noGames": ["Nenhuma partida ainda.", "No games yet.", "Todavía no hay partidas."],
  "st.individual": ["Individual", "Solo", "Individual"],
  "st.noRecords": ["Ainda não há recordes.", "No records yet.", "Todavía no hay récords."],
  "profile.nick": ["Nickname", "Nickname", "Apodo"],
  "nick.ph": ["Como a turma te chama", "What your friends call you", "Cómo te dicen tus amigos"],
  "profile.noNick": ["Sem nickname", "No nickname", "Sin apodo"],
  "profile.stats": ["Estatísticas", "Stats", "Estadísticas"],
  "profile.statsHelp": ["Salvas neste aparelho e, com a conta conectada, também na conta.", "Saved on this device and, with your account connected, in your account too.", "Guardadas en este dispositivo y, con la cuenta conectada, también en la cuenta."],
  "profile.byMode": ["Partidas por modo", "Games by mode", "Partidas por modo"],
  "profile.records": ["Recordes", "Records", "Récords"],
  "profile.online": ["Partidas online", "Online games", "Partidas online"],
  "profile.reset": ["Zerar estatísticas", "Reset stats", "Borrar estadísticas"],
  "profile.resetConfirm": ["Apagar estatísticas e recordes deste navegador?", "Delete stats and records from this browser?", "¿Borrar estadísticas y récords de este navegador?"],
  "account.enter": ["Entrar na conta Gamezi", "Sign in to Gamezi", "Entrar a Gamezi"],
  "account.connect": ["Conectar conta Gamezi", "Connect Gamezi account", "Conectar cuenta Gamezi"],
  "account.mine": ["Minha conta", "My account", "Mi cuenta"],
  "account.needSetup": ["Para salvar o perfil numa conta, o modo online precisa estar configurado.", "To save your profile to an account, online mode must be set up.", "Para guardar el perfil en una cuenta, el modo online tiene que estar configurado."],
  "account.connected": ["Conta Gamezi conectada: {email}. Perfil, estatísticas e recordes ficam salvos.", "Gamezi account connected: {email}. Profile, stats and records are saved.", "Cuenta Gamezi conectada: {email}. Perfil, estadísticas y récords quedan guardados."],
  "account.pitch": ["Entre na sua conta Gamezi, a mesma de todos os jogos, para salvar perfil, estatísticas e recordes e jogar em qualquer celular.", "Sign in to your Gamezi account, the same for every game, to save your profile, stats and records and play on any phone.", "Entra en tu cuenta Gamezi, la misma de todos los juegos, para guardar perfil, estadísticas y récords y jugar en cualquier celular."],
  "online.intro": ["Cada um no seu celular. Crie uma sala e mande o código (ou o link) para a turma.", "Everyone on their own phone. Create a room and send the code (or link) to your friends.", "Cada uno en su celular. Crea una sala y manda el código (o el enlace) al grupo."],
  "online.setup": ["<b>O modo online ainda não foi configurado.</b> Ele usa o Supabase (gratuito): o passo a passo está em <code>supabase/LEIAME.md</code>.", "<b>Online mode isn't set up yet.</b> It uses Supabase (free): see <code>supabase/LEIAME.md</code>.", "<b>El modo online todavía no está configurado.</b> Usa Supabase (gratis): mira <code>supabase/LEIAME.md</code>."],
  "online.nick": ["Seu nickname", "Your nickname", "Tu apodo"],
  "online.create": ["Criar sala", "Create room", "Crear sala"],
  "online.createHelp": ["Você escolhe o modo, o tempo e a lista, e começa quando todo mundo entrar.", "You pick the mode, time and list, and start when everyone's in.", "Eliges el modo, el tiempo y la lista, y empiezas cuando todos entren."],
  "online.join": ["Entrar numa sala", "Join a room", "Entrar a una sala"],
  "online.codePh": ["CÓDIGO", "CODE", "CÓDIGO"],
  "online.codeAria": ["Código da sala", "Room code", "Código de la sala"],
  "online.enter": ["Entrar", "Join", "Entrar"],
  "on.errNet": ["Não deu para conectar. Confira a internet.", "Couldn't connect. Check your internet.", "No se pudo conectar. Revisa tu internet."],
  "on.errSetup": ["O modo online ainda não foi configurado (veja supabase/LEIAME.md).", "Online mode isn't set up yet (see supabase/LEIAME.md).", "El modo online todavía no está configurado (mira supabase/LEIAME.md)."],
  "on.errAnon": ["Não deu para entrar. Ative o login anônimo no Supabase (veja supabase/LEIAME.md).", "Couldn't sign in. Enable anonymous sign-in on Supabase (see supabase/LEIAME.md).", "No se pudo entrar. Activa el inicio de sesión anónimo en Supabase (mira supabase/LEIAME.md)."],
  "on.errNick": ["Escolha um nickname antes de entrar.", "Choose a nickname first.", "Elige un apodo antes de entrar."],
  "on.creating": ["Criando sala…", "Creating room…", "Creando sala…"],
  "on.errCreate": ["Não deu para criar a sala. Tente de novo.", "Couldn't create the room. Try again.", "No se pudo crear la sala. Inténtalo de nuevo."],
  "on.errCode": ["O código da sala tem 5 letras.", "The room code has 5 letters.", "El código de la sala tiene 5 letras."],
  "on.errNotFound": ["Sala não encontrada. Confira o código.", "Room not found. Check the code.", "Sala no encontrada. Revisa el código."],
  "on.errStarted": ["A partida dessa sala já começou. Espere ela acabar.", "This room's game has already started. Wait for it to end.", "La partida de esta sala ya empezó. Espera a que termine."],
  "on.errFull": ["A sala está cheia (máximo de 8).", "The room is full (max 8).", "La sala está llena (máximo 8)."],
  "on.joining": ["Entrando…", "Joining…", "Entrando…"],
  "on.closed": ["A sala foi fechada.", "The room was closed.", "La sala se cerró."],
  "on.left": ["Você saiu da sala.", "You left the room.", "Saliste de la sala."],
  "on.hostClosed": ["O anfitrião fechou a sala.", "The host closed the room.", "El anfitrión cerró la sala."],
  "on.sending": ["Enviando \"{text}\"…", "Sending \"{text}\"…", "Enviando \"{text}\"…"],
  "on.hostDown": ["O anfitrião caiu. Esperando ele voltar…", "The host disconnected. Waiting for them to come back…", "El anfitrión se desconectó. Esperando que vuelva…"],
  "on.playerLeft": ["{nome} saiu da sala e perdeu a vez.", "{nome} left the room and lost their turn.", "{nome} salió de la sala y perdió el turno."],
  "on.historyEmpty": ["Jogue online para ver o histórico aqui.", "Play online to see your history here.", "Juega online para ver el historial aquí."],
  "on.historyNone": ["Nenhuma partida online ainda.", "No online games yet.", "Todavía no hay partidas online."],
  "lobby.invite": ["Convidar", "Invite", "Invitar"],
  "lobby.inviteText": ["Bora jogar Topzi! Entra na minha sala: {code}", "Let's play Topzi! Join my room: {code}", "¡Juguemos Topzi! Entra a mi sala: {code}"],
  "lobby.players": ["Jogadores", "Players", "Jugadores"],
  "lobby.start": ["Começar partida", "Start game", "Empezar partida"],
  "lobby.leave": ["Sair da sala", "Leave room", "Salir de la sala"],
  "lobby.you": ["você", "you", "tú"],
  "lobby.host": ["anfitrião", "host", "anfitrión"],
  "lobby.kick": ["Remover da sala", "Remove from room", "Quitar de la sala"],
  "lobby.kickConfirm": ["Remover {nome} da sala?", "Remove {nome} from the room?", "¿Quitar a {nome} de la sala?"],
  "lobby.noList": ["nenhuma lista escolhida", "no list chosen", "ninguna lista elegida"],
  "lobby.timer": ["{n} segundos por vez", "{n} seconds per turn", "{n} segundos por turno"],
  "lobby.noTimer": ["sem limite de tempo", "no time limit", "sin límite de tiempo"],
  "lobby.hostPicks": ["Quem escolhe é o anfitrião, mas você pode sugerir.", "The host picks, but you can suggest.", "Elige el anfitrión, pero puedes sugerir."],
  "lobby.changeSuggestion": ["Trocar sugestão", "Change suggestion", "Cambiar sugerencia"],
  "lobby.seeLists": ["Ver listas e sugerir", "See lists and suggest", "Ver listas y sugerir"],
  "lobby.mode": ["Modo", "Mode", "Modo"],
  "lobby.ready": ["Tudo pronto. Quando a turma estiver na sala, é só começar.", "All set. Once everyone's in the room, just start.", "Todo listo. Cuando el grupo esté en la sala, solo empieza."],
  "lobby.waiting": ["Esperando o anfitrião começar a partida…", "Waiting for the host to start…", "Esperando que el anfitrión empiece la partida…"],
  "lobby.pickList": ["Escolha a lista da partida.", "Choose the list for the game.", "Elige la lista de la partida."],
  "lobby.wrongSize": ["No {mode} a lista precisa ter {n} itens.", "In {mode} the list must have {n} items.", "En el {mode} la lista tiene que tener {n} ítems."],
  "lobby.teams2": ["O modo Times precisa de pelo menos 2 jogadores.", "Teams mode needs at least 2 players.", "El modo Equipos necesita al menos 2 jugadores."],
  "lobby.teamsEach": ["Cada time precisa de pelo menos um jogador.", "Each team needs at least one player.", "Cada equipo necesita al menos un jugador."],
  "lobby.sent": ["Sugestão enviada: {title}.", "Suggestion sent: {title}.", "Sugerencia enviada: {title}."],
  "lobby.suggestions": ["Sugestões da turma", "Suggestions from the group", "Sugerencias del grupo"],
  "lobby.suggestedBy": ["sugerida por {nomes}", "suggested by {nomes}", "sugerida por {nomes}"],
  "lobby.votes": ["{n} votos", "{n} votes", "{n} votos"],
  "lobby.chosen": ["escolhida", "chosen", "elegida"],
  "lobby.use": ["Usar", "Use", "Usar"],
});

// ───────────── como jogar e rodapé ─────────────
Object.assign(TEXTS, {
  "help.title": ["Como jogar", "How to play", "Cómo jugar"],
  "help.intro": [
    "Descubra os itens de uma lista que está em ordem, do mais óbvio ao mais difícil. O número de cada item é a pontuação dele.",
    "Find the items of a ranked list, from the most obvious to the hardest. Each item's number is how many points it's worth.",
    "Descubre los ítems de una lista ordenada, del más obvio al más difícil. El número de cada ítem es su puntuación.",
  ],
  "help.exCat": ["Geografia", "Geography", "Geografía"],
  "help.exTitle": ["Os 10 países mais populosos do mundo", "The 10 most populous countries in the world", "Los 10 países más poblados del mundo"],
  "help.exItem1": ["Índia", "India", "India"],
  "help.exItem10": ["México", "Mexico", "México"],
  "help.exItem9": ["Rússia", "Russia", "Rusia"],
  "help.exWrong": ["Japão", "Japan", "Japón"],
  "help.exHint": ["B… · 10 letras", "B… · 10 letters", "B… · 10 letras"],
  "help.ex1": [
    "Acertou o <b>nº 1</b>? Ganhou <b>1 ponto</b>. É o óbvio: quase todo mundo lembra.",
    "Got <b>No. 1</b>? That's <b>1 point</b>. It's the obvious one: almost everyone gets it.",
    "¿Acertaste el <b>n.º 1</b>? Ganas <b>1 punto</b>. Es lo obvio: casi todo el mundo lo recuerda.",
  ],
  "help.ex10": [
    "O último é o mais difícil e vale mais: o <b>nº 10</b> vale <b>10 pontos</b>. No Top 50, o nº 50 vale 50.",
    "The last one is the hardest and worth the most: <b>No. 10</b> is worth <b>10 points</b>. In Top 50, No. 50 is worth 50.",
    "El último es el más difícil y vale más: el <b>n.º 10</b> vale <b>10 puntos</b>. En el Top 50, el n.º 50 vale 50.",
  ],
  "help.exHidden": [
    "Os itens que ninguém achou ficam <b>escondidos</b> até alguém acertar ou a partida acabar.",
    "Items nobody has found stay <b>hidden</b> until someone gets them or the game ends.",
    "Los ítems que nadie encontró quedan <b>ocultos</b> hasta que alguien acierte o termine la partida.",
  ],
  "help.exMiss": [
    "Chutou algo que <b>não está na lista</b>? Passa a vez sem pontos. Jogando com vidas, ainda perde uma.",
    "Guessed something that's <b>not on the list</b>? Your turn passes with no points. Playing with lives, you also lose one.",
    "¿Dijiste algo que <b>no está en la lista</b>? Pasa el turno sin puntos. Jugando con vidas, además pierdes una.",
  ],
  "help.exHintText": [
    "Com vidas, dá para trocar <b>uma vida por uma dica</b>: a primeira letra e o tamanho de um item.",
    "With lives on, you can trade <b>a life for a hint</b>: the first letter and length of an item.",
    "Con vidas, puedes cambiar <b>una vida por una pista</b>: la primera letra y el largo de un ítem.",
  ],
  "help.exMissed": [
    "No fim, o que ninguém achou aparece <b>tracejado</b>. Na Equipe contra a lista, esses pontos vão para a lista.",
    "At the end, whatever nobody found shows up <b>dashed</b>. In Team vs. the list, those points go to the list.",
    "Al final, lo que nadie encontró aparece <b>punteado</b>. En Equipo contra la lista, esos puntos son para la lista.",
  ],
  "help.guessTitle": ["Vale do seu jeito", "Say it your way", "Vale a tu manera"],
  "help.guess": [
    "Maiúsculas e acentos não importam, singular e plural valem igual, siglas e apelidos também (“EUA”, “BH”) e um errinho de digitação passa. Nas listas de frases, basta acertar a ideia principal.",
    "Capitals and accents don't matter, singular and plural count the same, so do abbreviations and nicknames (“USA”, “NYC”), and a small typo is fine. In lists of sayings, the main idea is enough.",
    "Mayúsculas y tildes no importan, singular y plural valen igual, siglas y apodos también (“EE. UU.”, “CDMX”) y un error de tipeo pasa. En las listas de frases, basta con acertar la idea principal.",
  ],
  "help.modesTitle": ["Modos", "Modes", "Modos"],
  "help.modeTop": [
    "<b>Top 10, 30 e 50:</b> sozinho, 1v1 ou todos contra todos. Quem somar mais pontos vence.",
    "<b>Top 10, 30 and 50:</b> solo, 1v1 or free-for-all. Most points wins.",
    "<b>Top 10, 30 y 50:</b> solo, 1v1 o todos contra todos. Gana quien sume más puntos.",
  ],
  "help.modeTeam": [
    "<b>Equipe contra a lista:</b> todos jogam juntos. A equipe vence se fizer mais da metade dos pontos.",
    "<b>Team vs. the list:</b> everyone plays together. The team wins with more than half the points.",
    "<b>Equipo contra la lista:</b> todos juegan juntos. El equipo gana si hace más de la mitad de los puntos.",
  ],
  "help.modeMorte": [
    "<b>Morte súbita:</b> cada um tem uma vida só. Errou, está fora. Quem somar mais pontos vence.",
    "<b>Sudden death:</b> everyone has a single life. One miss and you're out. Most points wins.",
    "<b>Muerte súbita:</b> cada uno tiene una sola vida. Si fallas, quedas fuera. Gana quien sume más puntos.",
  ],
  "help.modeTimes": [
    "<b>Times:</b> Time Vermelho contra Time Preto. A vez alterna entre os times.",
    "<b>Teams:</b> Red Team against Black Team. Turns alternate between the teams.",
    "<b>Equipos:</b> Equipo Rojo contra Equipo Negro. El turno se alterna entre los equipos.",
  ],
  "help.turn": [
    "Na sua vez, chute ou passe a vez. A partida acaba quando todos os itens aparecem, quando todo mundo passa seguido ou quando acabam as vidas.",
    "On your turn, guess or pass. The game ends when every item is found, when everyone passes in a row or when lives run out.",
    "En tu turno, adivina o pasa. La partida termina cuando aparecen todos los ítems, cuando todos pasan seguidos o cuando se acaban las vidas.",
  ],
  "help.dailyTitle": ["Lista do dia e online", "Daily list and online", "Lista del día y online"],
  "help.daily": [
    "Todo dia tem uma lista nova, igual para todo mundo, com 3 vidas e resultado para compartilhar. No “Jogar online”, cada um usa o próprio celular: crie uma sala e mande o código para a turma.",
    "Every day there's a new list, the same for everyone, with 3 lives and a result to share. In “Play online”, everyone uses their own phone: create a room and send the code to your friends.",
    "Cada día hay una lista nueva, igual para todos, con 3 vidas y un resultado para compartir. En “Jugar online”, cada uno usa su propio celular: crea una sala y manda el código al grupo.",
  ],
  "foot.terms": ["Termos de uso", "Terms of use", "Términos de uso"],
  "foot.gamezi": ["Mais jogos no Gamezi", "More games on Gamezi", "Más juegos en Gamezi"],
  "foot.privacy": ["Privacidade", "Privacy", "Privacidad"],
});
